import json
import subprocess
import sys
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tech_route_maker.quality import build_quality_report  # noqa: E402


CORE_FORMATS = "pptx,svg,drawio,drawio-code,excalidraw,mermaid,html,markdown,json"


def write_text(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def ev(path, note):
    return [
        {
            "kind": "source",
            "source_id": "source_1",
            "path": path,
            "locator": note,
            "quote_or_note": note,
        }
    ]


def node(node_id, label, detail, tag, path, note, confidence="high"):
    return {
        "id": node_id,
        "label": label,
        "detail": detail,
        "tag": tag,
        "node_type": tag,
        "confidence": confidence,
        "is_inferred": False,
        "evidence": ev(path, note),
    }


def stage(stage_id, title, order, summary, nodes):
    return {"id": stage_id, "title": title, "order": order, "summary": summary, "nodes": nodes}


def edge(edge_id, source, target, label, kind="flow", confidence="medium"):
    return {"id": edge_id, "from": source, "to": target, "label": label, "kind": kind, "confidence": confidence, "evidence": []}


def domain_context(
    discipline,
    subfield,
    project_type,
    research_object,
    method_family,
    application_area,
    data_or_materials,
    technical_objects,
    domain_constraints,
    evaluation_metrics,
    expected_outputs,
    domain_profile=None,
    terminology=None,
    source="demo brief",
    confidence="high",
):
    return {
        "discipline": discipline,
        "subfield": subfield,
        "project_type": project_type,
        "research_object": research_object,
        "method_family": method_family,
        "application_area": application_area,
        "data_or_materials": data_or_materials,
        "technical_objects": technical_objects,
        "domain_constraints": domain_constraints,
        "evaluation_metrics": evaluation_metrics,
        "expected_outputs": expected_outputs,
        "terminology": terminology or {},
        "domain_profile": domain_profile or {},
        "source": source,
        "confidence": confidence,
    }


def finalize(route):
    route.setdefault("route_version", "0.2.0")
    route.setdefault("assumptions", [])
    route.setdefault("unresolved_questions", [])
    route.setdefault("citations", [])
    route.setdefault("renderer_overrides", {})
    route["quality_report"] = build_quality_report(route)
    return route


def academic_route():
    path = "examples/academic-paper-demo/brief.md"
    return finalize(
        {
            "title": "PV Surface Defect Detection Method Route",
            "subtitle": "Academic method framework demo generated by tech-route-maker",
            "selected_preset": "academic-method",
            "layout": "academic-method-framework",
            "style": "academic-blue",
            "domain_context": domain_context(
                discipline="Computer science and renewable energy",
                subfield="Computer vision for photovoltaic defect detection",
                project_type="paper method figure",
                research_object="PV module surface and thermal defects",
                method_family="deep learning object detection",
                application_area="PV inspection and operation maintenance",
                data_or_materials=["RGB images", "infrared images", "annotated defect labels"],
                technical_objects=["dataset annotation", "multimodal feature fusion", "detector backbone", "ablation study", "defect report"],
                domain_constraints=["small targets", "class imbalance", "field imaging variation", "real-time inference"],
                evaluation_metrics=["mAP", "precision", "recall", "FPS", "Params"],
                expected_outputs=["editable method route", "validated detector", "defect diagnosis report"],
                domain_profile={
                    "task_type": "object detection",
                    "data_modalities": ["RGB", "infrared"],
                    "model_family": ["YOLO", "CNN", "feature fusion", "attention"],
                },
            ),
            "reader_question": "How does the method move from multi-source image evidence to validated defect results?",
            "reader_path": ["Goal", "Data", "Method", "Training", "Validation", "Output"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "paper",
                "source_files": [{"path": path, "kind": "document", "description": "Academic paper demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("goal", "Research Goal", 1, "Define the detection task and evaluation target.", [
                    node("goal_task", "Define defect task", "Identify visible and thermal defect categories in PV module images.", "objective", path, "Detection task"),
                    node("goal_metric", "Set evaluation metrics", "Use precision, recall, mAP, inference speed, and failure cases as evaluation anchors.", "objective", path, "Evaluation metrics"),
                ]),
                stage("data", "Data Evidence", 2, "Build traceable RGB and infrared image evidence.", [
                    node("data_collect", "Collect RGB and IR images", "Gather complementary visible and infrared image evidence.", "input", path, "Multimodal images"),
                    node("data_align", "Align and annotate defects", "Register image pairs and label defect locations or classes.", "input", path, "Alignment and annotation"),
                    node("data_split", "Prepare train test sets", "Clean low-quality samples and split training, validation, and test data.", "implementation", path, "Dataset split"),
                ]),
                stage("method", "Method Design", 3, "Convert evidence into a defect detection model.", [
                    node("method_baseline", "Build baseline detector", "Start from a general object detector as the controlled baseline.", "method", path, "Baseline detector"),
                    node("method_fusion", "Fuse multimodal features", "Combine RGB and infrared features for stronger defect representation.", "method", path, "Feature fusion"),
                    node("method_attention", "Enhance weak regions", "Use feature enhancement to emphasize weak-texture or small defect regions.", "method", path, "Region enhancement"),
                ]),
                stage("training", "Training Validation", 4, "Train and check whether each design choice contributes.", [
                    node("training_loss", "Optimize detection losses", "Balance classification, localization, and confidence losses.", "implementation", path, "Loss optimization"),
                    node("training_ablation", "Run ablation studies", "Verify fusion, enhancement, and training strategy contributions.", "validation", path, "Ablation plan"),
                    node("training_infer", "Infer defect candidates", "Run inference and filter candidates by confidence.", "implementation", path, "Inference plan"),
                ]),
                stage("output", "Validation Output", 5, "Connect model results to paper-ready evidence.", [
                    node("output_metrics", "Report quantitative gains", "Compare against baselines with mAP, precision, recall, and speed.", "validation", path, "Metric report"),
                    node("output_visual", "Explain visual results", "Show detections, heat responses, and failure cases for interpretability.", "output", path, "Visual explanation"),
                    node("output_report", "Generate defect report", "Summarize defect class, location, confidence, and maintenance priority.", "output", path, "Defect report"),
                ]),
            ],
            "edges": [
                edge("e1", "goal_task", "goal_metric", "defines"),
                edge("e2", "goal_metric", "data_collect", "guides"),
                edge("e3", "data_collect", "data_align", "aligns"),
                edge("e4", "data_align", "data_split", "prepares"),
                edge("e5", "data_split", "method_baseline", "feeds"),
                edge("e6", "method_baseline", "method_fusion", "extends"),
                edge("e7", "method_fusion", "method_attention", "enhances"),
                edge("e8", "method_attention", "training_loss", "optimizes"),
                edge("e9", "training_loss", "training_ablation", "tests"),
                edge("e10", "training_ablation", "training_infer", "selects"),
                edge("e11", "training_infer", "output_metrics", "evaluates"),
                edge("e12", "output_metrics", "output_visual", "explains"),
                edge("e13", "output_visual", "output_report", "reports"),
            ],
        }
    )


def thesis_route():
    path = "examples/thesis-proposal-demo/brief.md"
    return finalize(
        {
            "title": "Photovoltaic Self-Cleaning Coating Proposal Route",
            "subtitle": "Thesis proposal technical route generated by tech-route-maker",
            "selected_preset": "thesis-proposal",
            "layout": "proposal-matrix-route",
            "style": "presentation-clean",
            "domain_context": domain_context(
                discipline="Materials science and photovoltaic engineering",
                subfield="Self-cleaning coating for PV cover glass",
                project_type="thesis proposal technical route",
                research_object="transparent self-cleaning coating on PV glass",
                method_family="material preparation, characterization and performance testing",
                application_area="PV module surface protection and efficiency retention",
                data_or_materials=["coating precursors", "PV cover glass", "dust and water contamination samples"],
                technical_objects=["coating chemistry", "micro/nano texture", "surface morphology", "wettability", "durability test"],
                domain_constraints=["transparency retention", "outdoor durability", "process scalability", "PV compatibility"],
                evaluation_metrics=["contact angle", "sliding angle", "transmittance", "abrasion resistance", "power retention"],
                expected_outputs=["proposal route", "coating samples", "performance dataset", "thesis chapter structure"],
                domain_profile={
                    "material_route": "design-preparation-characterization-testing-mechanism",
                    "test_types": ["wettability", "optical", "durability", "PV power impact"],
                },
            ),
            "reader_question": "How does the proposal connect coating design, performance testing, and PV application value?",
            "reader_path": ["Objective", "Research Content", "Key Technology", "Validation", "Expected Outcomes"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "document", "description": "Thesis proposal demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("objective", "Research Objective", 1, "Define the PV self-cleaning coating research target.", [
                    node("objective_problem", "Reduce surface contamination", "Address dust, water, and ice accumulation on PV cover glass.", "objective", path, "Research problem"),
                    node("objective_value", "Protect optical efficiency", "Balance surface protection with transparency and energy-yield relevance.", "objective", path, "PV value"),
                ]),
                stage("content", "Research Content", 2, "Organize the proposal into material, structure, and performance content.", [
                    node("content_material", "Select coating chemistry", "Choose low-surface-energy chemistry and compatible matrix materials.", "method", path, "Material selection"),
                    node("content_texture", "Design micro nano texture", "Construct surface texture for hydrophobicity and contaminant removal.", "method", path, "Texture design"),
                    node("content_process", "Plan scalable process", "Compare spraying, dip-coating, or sol-gel routes for PV glass.", "implementation", path, "Process route"),
                ]),
                stage("technology", "Key Technology", 3, "Resolve the technical constraints behind coating performance.", [
                    node("technology_wettability", "Tune wetting behavior", "Use contact angle and sliding angle to guide surface design.", "method", path, "Wetting behavior"),
                    node("technology_durability", "Improve durability", "Evaluate abrasion, UV exposure, humidity, and thermal cycling.", "validation", path, "Durability design"),
                    node("technology_transparency", "Maintain transparency", "Control roughness and thickness to limit optical loss.", "validation", path, "Transparency constraint"),
                ]),
                stage("validation", "Experimental Validation", 4, "Verify coating function and PV relevance.", [
                    node("validation_surface", "Characterize surface structure", "Use morphology and chemical characterization to confirm coating formation.", "validation", path, "Surface characterization"),
                    node("validation_cleaning", "Test self-cleaning function", "Compare dust removal, water shedding, and icing behavior.", "validation", path, "Function tests"),
                    node("validation_power", "Measure PV impact", "Track transmittance and power output before and after contamination.", "validation", path, "PV performance"),
                ]),
                stage("outcome", "Expected Outcomes", 5, "Convert experiments into proposal deliverables.", [
                    node("outcome_route", "Form technical route", "Produce a defensible route from material design to PV performance validation.", "output", path, "Technical route"),
                    node("outcome_thesis", "Support thesis chapters", "Connect background, method, experiment, results, and discussion chapters.", "output", path, "Thesis output"),
                ]),
            ],
            "edges": [
                edge("e1", "objective_problem", "objective_value", "frames"),
                edge("e2", "objective_value", "content_material", "guides"),
                edge("e3", "content_material", "content_texture", "supports"),
                edge("e4", "content_texture", "content_process", "scales"),
                edge("e5", "content_process", "technology_wettability", "requires"),
                edge("e6", "technology_wettability", "technology_durability", "balances"),
                edge("e7", "technology_durability", "technology_transparency", "constrains"),
                edge("e8", "technology_transparency", "validation_surface", "checks"),
                edge("e9", "validation_surface", "validation_cleaning", "tests"),
                edge("e10", "validation_cleaning", "validation_power", "links"),
                edge("e11", "validation_power", "outcome_route", "supports"),
                edge("e12", "outcome_route", "outcome_thesis", "writes"),
            ],
        }
    )


def energy_route():
    path = "examples/engineering-energy-system-demo/brief.md"
    return finalize(
        {
            "title": "Campus Integrated Energy System Technical Route",
            "subtitle": "Source-grid-load-storage engineering route generated by tech-route-maker",
            "selected_preset": "engineering-system",
            "layout": "engineering-architecture-route",
            "style": "dark-technical",
            "domain_context": domain_context(
                discipline="Energy engineering",
                subfield="Campus integrated energy system planning",
                project_type="engineering report route",
                research_object="source-grid-load-storage campus energy system",
                method_family="system modelling, optimization and scenario validation",
                application_area="campus low-carbon energy planning and operation",
                data_or_materials=["electric load profile", "thermal load profile", "weather data", "tariff data", "equipment parameters"],
                technical_objects=["PV", "energy storage", "grid exchange", "heat pump", "dispatch strategy", "KPI evaluation"],
                domain_constraints=["grid interaction limits", "equipment capacity", "weather uncertainty", "budget", "implementation sequence"],
                evaluation_metrics=["cost", "carbon emissions", "renewable utilization", "peak shaving", "reliability"],
                expected_outputs=["capacity plan", "operation strategy", "scenario comparison", "engineering deliverables"],
                domain_profile={
                    "system_scope": "source-grid-load-storage",
                    "analysis_types": ["planning optimization", "dispatch simulation", "sensitivity analysis"],
                },
            ),
            "reader_question": "How does the engineering route turn campus demand evidence into a validated source-grid-load-storage configuration?",
            "reader_path": ["Boundary", "Data", "Configuration", "Operation", "Validation", "Deliverables"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "engineering",
                "source_files": [{"path": path, "kind": "document", "description": "Engineering energy system demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "engineering",
                "demo": True,
            },
            "stages": [
                stage("boundary", "System Boundary", 1, "Define the campus energy boundary and objectives.", [
                    node("boundary_scope", "Define campus boundary", "Identify buildings, loads, energy assets, and grid connection scope.", "objective", path, "System boundary"),
                    node("boundary_targets", "Set planning targets", "Balance cost, carbon reduction, reliability, and renewable utilization.", "objective", path, "Planning targets"),
                ]),
                stage("data", "Source Load Data", 2, "Build the evidence base for configuration.", [
                    node("data_load", "Profile electric thermal load", "Construct hourly electricity, heating, cooling, and flexible load profiles.", "input", path, "Load profiles"),
                    node("data_resource", "Assess renewable resources", "Estimate solar, wind, storage, and available land or roof resources.", "input", path, "Resource assessment"),
                    node("data_tariff", "Collect tariff constraints", "Include tariff, demand charge, carbon factor, and grid interaction limits.", "input", path, "Tariff and constraints"),
                ]),
                stage("model", "Configuration Model", 3, "Optimize source-grid-load-storage sizing.", [
                    node("model_assets", "Model candidate assets", "Represent PV, storage, heat pump, grid purchase, and controllable loads.", "method", path, "Candidate assets"),
                    node("model_objective", "Optimize multi-objective sizing", "Solve cost-carbon-reliability tradeoffs under engineering constraints.", "method", path, "Optimization objective"),
                    node("model_scenarios", "Compare planning scenarios", "Run baseline, renewable-priority, storage-priority, and low-carbon scenarios.", "validation", path, "Scenario comparison"),
                ]),
                stage("operation", "Operation Strategy", 4, "Turn the planning result into operating logic.", [
                    node("operation_dispatch", "Build dispatch strategy", "Coordinate PV self-consumption, storage charge-discharge, and grid exchange.", "implementation", path, "Dispatch strategy"),
                    node("operation_control", "Define control hierarchy", "Separate day-ahead planning, intraday correction, and real-time control.", "implementation", path, "Control hierarchy"),
                ]),
                stage("validation", "Validation Output", 5, "Verify engineering feasibility and deliverables.", [
                    node("validation_kpi", "Evaluate system KPIs", "Report cost, carbon, renewable utilization, peak shaving, and reliability metrics.", "validation", path, "KPI evaluation"),
                    node("validation_sensitivity", "Run sensitivity checks", "Test tariff, weather, load growth, and equipment-cost uncertainty.", "validation", path, "Sensitivity analysis"),
                    node("validation_deliver", "Deliver configuration plan", "Output capacity plan, operation plan, risk notes, and implementation sequence.", "output", path, "Deliverables"),
                ]),
            ],
            "edges": [
                edge("e1", "boundary_scope", "boundary_targets", "sets"),
                edge("e2", "boundary_targets", "data_load", "requires"),
                edge("e3", "data_load", "data_resource", "combines"),
                edge("e4", "data_resource", "data_tariff", "constrains"),
                edge("e5", "data_tariff", "model_assets", "feeds"),
                edge("e6", "model_assets", "model_objective", "optimizes"),
                edge("e7", "model_objective", "model_scenarios", "compares"),
                edge("e8", "model_scenarios", "operation_dispatch", "selects"),
                edge("e9", "operation_dispatch", "operation_control", "organizes"),
                edge("e10", "operation_control", "validation_kpi", "validates"),
                edge("e11", "validation_kpi", "validation_sensitivity", "stress tests"),
                edge("e12", "validation_sensitivity", "validation_deliver", "delivers"),
            ],
        }
    )


def workflow_route():
    path = "examples/agent-workflow-demo/brief.md"
    return finalize(
        {
            "title": "Agent Workflow For Editable Route Diagrams",
            "subtitle": "Workflow pipeline demo generated by tech-route-maker",
            "selected_preset": "workflow-pipeline",
            "layout": "horizontal-stages",
            "style": "minimal-gray",
            "domain_context": domain_context(
                discipline="Software engineering",
                subfield="Agent workflow for editable diagram generation",
                project_type="workflow documentation route",
                research_object="route-diagram generation agent workflow",
                method_family="source-grounded extraction, schema validation and editable rendering",
                application_area="agent skills and technical documentation",
                data_or_materials=["source documents", "project files", "route JSON", "rendered diagram outputs"],
                technical_objects=["source intake", "evidence extraction", "route schema", "render scripts", "quality report"],
                domain_constraints=["untrusted source files", "format editability", "evidence traceability", "agent portability"],
                evaluation_metrics=["validation pass", "evidence coverage", "editable output availability", "warning clarity"],
                expected_outputs=["tech-route.json", "PPTX", "SVG", "Draw.io", "HTML preview", "QUALITY_REPORT.md"],
                domain_profile={
                    "workflow_type": "agent skill pipeline",
                    "render_targets": ["PPTX", "SVG", "Draw.io", "HTML", "Markdown", "JSON"],
                },
            ),
            "reader_question": "How does the agent convert technical source material into editable, reviewable route diagrams?",
            "reader_path": ["Source Intake", "Evidence Extraction", "Route JSON", "Editable Rendering", "Quality Review"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "workflow",
                "source_files": [{"path": path, "kind": "document", "description": "Agent workflow demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "technical",
                "demo": True,
            },
            "stages": [
                stage("intake", "Source Intake", 1, "Collect and scope the technical source material.", [
                    node("intake_scope", "Confirm source scope", "Use a repository, paper, proposal, brief, or pasted notes as the evidence boundary.", "input", path, "Source scope"),
                    node("intake_safety", "Avoid unsafe execution", "Read project files without running untrusted code unless the user approves.", "input", path, "Safety rule"),
                ]),
                stage("extract", "Evidence Extraction", 2, "Extract route elements from source evidence.", [
                    node("extract_objective", "Find objectives and gaps", "Identify the target problem, reader question, and expected result.", "method", path, "Objective extraction"),
                    node("extract_steps", "Extract method steps", "Collect non-droppable stages, modules, inputs, outputs, and validation logic.", "method", path, "Step extraction"),
                    node("extract_evidence", "Attach evidence notes", "Record source paths, locators, and notes for visible nodes.", "validation", path, "Evidence linking"),
                ]),
                stage("model", "Route JSON", 3, "Create an auditable source model before drawing.", [
                    node("model_schema", "Build route schema", "Write stages, nodes, edges, confidence, assumptions, and unresolved questions.", "implementation", path, "Schema build"),
                    node("model_validate", "Validate route model", "Check version, preset, evidence, edge endpoints, and label length.", "validation", path, "Validation"),
                ]),
                stage("render", "Editable Rendering", 4, "Render the same route into editable outputs.", [
                    node("render_pptx", "Render PPTX shapes", "Create PowerPoint-native shapes, text boxes, and connectors.", "output", path, "PPTX render"),
                    node("render_svg", "Render SVG vector", "Generate vector shapes and text for design-tool editing.", "output", path, "SVG render"),
                    node("render_drawio", "Render Draw.io cells", "Export editable diagrams.net nodes and edges for maintenance.", "output", path, "Draw.io render"),
                ]),
                stage("review", "Quality Review", 5, "Make warnings and manual revision needs visible.", [
                    node("review_report", "Generate quality report", "Summarize evidence coverage, inferred nodes, warnings, and manual review tasks.", "validation", path, "Quality report"),
                    node("review_iterate", "Revise editable files", "Let the user adjust wording, color, spacing, and route logic in editable outputs.", "feedback", path, "Iteration loop"),
                ]),
            ],
            "edges": [
                edge("e1", "intake_scope", "intake_safety", "bounds"),
                edge("e2", "intake_safety", "extract_objective", "starts"),
                edge("e3", "extract_objective", "extract_steps", "structures"),
                edge("e4", "extract_steps", "extract_evidence", "grounds"),
                edge("e5", "extract_evidence", "model_schema", "writes"),
                edge("e6", "model_schema", "model_validate", "checks"),
                edge("e7", "model_validate", "render_pptx", "renders"),
                edge("e8", "model_validate", "render_svg", "renders"),
                edge("e9", "model_validate", "render_drawio", "renders"),
                edge("e10", "render_pptx", "review_report", "reviews"),
                edge("e11", "review_report", "review_iterate", "improves"),
                edge("e12", "review_iterate", "model_schema", "updates", "feedback"),
            ],
        }
    )


def campaign_route():
    path = "examples/legacy-campaign-route-demo/brief.md"
    return finalize(
        {
            "title": "Legacy Campaign Strategy Route",
            "subtitle": "Experimental campaign route retained for explicit advertising requests",
            "selected_preset": "custom",
            "layout": "campaign-strategy-map",
            "style": "advertising-clean-campaign",
            "domain_context": domain_context(
                discipline="Marketing",
                subfield="Campaign strategy mapping",
                project_type="legacy campaign route",
                research_object="audience-to-channel campaign workflow",
                method_family="audience analysis, message design and channel measurement",
                application_area="commercial campaign planning",
                data_or_materials=["audience brief", "channel plan", "campaign metrics"],
                technical_objects=["audience segment", "insight", "message", "channel", "measurement"],
                domain_constraints=["brand consistency", "budget", "timing", "channel attribution"],
                evaluation_metrics=["reach", "conversion", "engagement", "cost per action"],
                expected_outputs=["campaign map", "channel plan", "measurement report"],
                confidence="medium",
            ),
            "reader_question": "How does the campaign connect audience insight to measurable adoption?",
            "reader_path": ["Audience", "Insight", "Message", "Channels", "Measurement"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "legacy-campaign",
                "source_files": [{"path": path, "kind": "document", "description": "Legacy campaign demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "campaign",
                "demo": True,
                "legacy": True,
            },
            "stages": [
                stage("audience", "Audience", 1, "Identify who the campaign must persuade.", [
                    node("audience_segments", "Map user segments", "Target researchers, lab managers, and academic teams.", "input", path, "Audience"),
                    node("audience_jobs", "Clarify workflow jobs", "Separate paper figures, proposal routes, and reporting needs.", "input", path, "Jobs"),
                ]),
                stage("insight", "Insight", 2, "Find the adoption driver.", [
                    node("insight_editable", "Lead with editability", "Emphasize editable, evidence-linked route diagrams.", "method", path, "Insight"),
                    node("insight_friction", "Remove drawing friction", "Show source-to-route workflow instead of manual redrawing.", "method", path, "Pain point"),
                ]),
                stage("message", "Message", 3, "Turn insight into positioning.", [
                    node("message_position", "Position workflow value", "Frame the tool as a source-to-editable-diagram workflow.", "method", path, "Positioning"),
                    node("message_proof", "Show demo proof", "Use README, gallery, and editable files as proof.", "implementation", path, "Proof"),
                ]),
                stage("channels", "Channels", 4, "Distribute proof-oriented content.", [
                    node("channels_github", "Use GitHub hub", "Anchor examples, install instructions, and release notes on GitHub.", "deployment", path, "GitHub"),
                    node("channels_content", "Publish demo content", "Share short videos, posts, and lab-demo decks.", "deployment", path, "Content"),
                ]),
                stage("measure", "Measurement", 5, "Connect content activity to adoption signals.", [
                    node("measure_metrics", "Track adoption signals", "Measure stars, demo runs, issue feedback, and trials.", "validation", path, "Metrics"),
                    node("measure_feedback", "Feed back issues", "Classify onboarding, layout, and output-format feedback.", "feedback", path, "Feedback"),
                ]),
            ],
            "edges": [
                edge("e1", "audience_segments", "audience_jobs", "segments"),
                edge("e2", "audience_jobs", "insight_editable", "reveals"),
                edge("e3", "insight_editable", "insight_friction", "frames"),
                edge("e4", "insight_friction", "message_position", "shapes"),
                edge("e5", "message_position", "message_proof", "proves"),
                edge("e6", "message_proof", "channels_github", "anchors"),
                edge("e7", "channels_github", "channels_content", "extends"),
                edge("e8", "channels_content", "measure_metrics", "drives"),
                edge("e9", "measure_metrics", "measure_feedback", "learns"),
                edge("e10", "measure_feedback", "message_position", "optimizes", "feedback"),
            ],
        }
    )


def academic_route_cn():
    path = "examples/academic-paper-demo/brief.md"
    return finalize(
        {
            "title": "多模态光伏缺陷检测方法技术路线图",
            "subtitle": "中文论文方法框架示例：从图像证据到可验证检测结果",
            "selected_preset": "academic-paper-framework-cn",
            "layout": "cn-research-method-matrix",
            "style": "research-ppt-blue",
            "domain_context": domain_context(
                discipline="计算机科学与新能源工程",
                subfield="光伏缺陷检测中的计算机视觉方法",
                project_type="论文方法框架图",
                research_object="光伏组件表面与热异常缺陷",
                method_family="深度学习目标检测与多模态特征融合",
                application_area="光伏电站巡检与智能运维",
                data_or_materials=["可见光图像", "红外图像", "缺陷标注", "测试样本"],
                technical_objects=["数据标注", "样本增强", "特征融合", "检测网络", "消融实验"],
                domain_constraints=["小目标缺陷", "样本不均衡", "现场成像差异", "实时推理"],
                evaluation_metrics=["mAP", "Precision", "Recall", "FPS", "参数量"],
                expected_outputs=["论文方法图", "检测模型", "对比实验结果", "缺陷诊断报告"],
                domain_profile={
                    "task_type": "object detection",
                    "data_modalities": ["RGB", "infrared"],
                    "model_family": ["YOLO", "CNN", "attention", "feature fusion"],
                },
            ),
            "reader_question": "该方法如何从多源图像证据走向可验证的缺陷检测结果？",
            "reader_path": ["研究目标", "数据证据", "方法设计", "训练验证", "结果输出"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "paper",
                "source_files": [{"path": path, "kind": "document", "description": "Chinese academic paper demo brief"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("goal", "研究目标", 1, "明确检测任务、指标体系和论文图需要回答的问题。", [
                    node("goal_task", "明确缺陷检测任务", "识别光伏组件可见光和红外图像中的缺陷类别、位置与置信度。", "objective", path, "Detection task"),
                    node("goal_metric", "设定评价指标", "围绕 precision、recall、mAP、推理速度和失败案例组织验证逻辑。", "objective", path, "Evaluation metrics"),
                ]),
                stage("data", "数据证据", 2, "建立 RGB 与红外图像输入，并形成可训练样本。", [
                    node("data_collect", "采集多模态图像", "收集 RGB 图像和红外热图，作为缺陷检测的互补输入。", "input", path, "Multimodal images"),
                    node("data_align", "配准并标注缺陷", "对齐 RGB/IR 图像，并标注缺陷边界或类别。", "input", path, "Alignment and annotation"),
                    node("data_split", "划分训练样本", "清洗低质量样本，划分训练、验证和测试数据。", "implementation", path, "Dataset split"),
                ]),
                stage("method", "方法设计", 3, "突出论文方法的主要创新模块。", [
                    node("method_baseline", "建立基线检测器", "以通用目标检测器作为基础框架和对照基线。", "method", path, "Baseline detector"),
                    node("method_fusion", "构建跨模态融合", "融合 RGB 与红外特征，提升缺陷区域表达能力。", "method", path, "Feature fusion"),
                    node("method_attention", "增强关键区域感知", "通过特征增强模块突出弱纹理、小目标或热异常区域。", "method", path, "Region enhancement"),
                ]),
                stage("training", "训练验证", 4, "从模型训练走向稳定推理。", [
                    node("training_loss", "优化检测损失", "平衡分类、定位和置信度损失，提升检测稳定性。", "implementation", path, "Loss optimization"),
                    node("training_ablation", "开展消融实验", "逐项验证融合模块、增强模块和训练策略的贡献。", "validation", path, "Ablation plan"),
                    node("training_infer", "推理并筛选结果", "对未见图像执行推理，并按置信度筛选缺陷结果。", "implementation", path, "Inference plan"),
                ]),
                stage("output", "结果输出", 5, "把技术路线连接到论文证据和应用结果。", [
                    node("output_metrics", "完成指标评估", "通过基线对比、mAP、precision 和 recall 验证方法有效性。", "validation", path, "Metric report"),
                    node("output_visual", "生成可视化解释", "输出检测框、热区响应和失败案例，支撑论文图表。", "output", path, "Visual explanation"),
                    node("output_report", "输出缺陷报告", "形成缺陷类别、位置、置信度和维护建议。", "output", path, "Defect report"),
                ]),
            ],
            "edges": [
                edge("e1", "goal_task", "goal_metric", "定义指标"),
                edge("e2", "goal_metric", "data_collect", "指导采集"),
                edge("e3", "data_collect", "data_align", "配准标注"),
                edge("e4", "data_align", "data_split", "形成样本"),
                edge("e5", "data_split", "method_baseline", "输入模型"),
                edge("e6", "method_baseline", "method_fusion", "扩展"),
                edge("e7", "method_fusion", "method_attention", "增强"),
                edge("e8", "method_attention", "training_loss", "优化"),
                edge("e9", "training_loss", "training_ablation", "验证贡献"),
                edge("e10", "training_ablation", "training_infer", "选择方案"),
                edge("e11", "training_infer", "output_metrics", "评价"),
                edge("e12", "output_metrics", "output_visual", "解释"),
                edge("e13", "output_visual", "output_report", "汇总"),
            ],
        }
    )


def thesis_route_cn():
    path = "examples/thesis-proposal-demo/brief.md"
    return finalize(
        {
            "title": "光伏自清洁涂层开题技术路线图",
            "subtitle": "中文开题报告示例：材料设计、性能测试与光伏应用验证",
            "selected_preset": "chinese-thesis-proposal",
            "layout": "cn-a4-stage-route",
            "style": "research-ppt-blue",
            "domain_context": domain_context(
                discipline="材料科学与新能源工程",
                subfield="光伏玻璃自清洁涂层",
                project_type="开题报告技术路线图",
                research_object="透明自清洁涂层及其光伏应用",
                method_family="材料设计、制备、表征与性能验证",
                application_area="光伏组件表面防护与发电效率保持",
                data_or_materials=["涂层前驱体", "光伏玻璃基底", "污染物样本", "环境老化样本"],
                technical_objects=["低表面能化学", "微纳结构", "润湿行为", "耐久性", "透光性"],
                domain_constraints=["透光率保持", "户外耐久性", "工艺可放大", "组件兼容性"],
                evaluation_metrics=["接触角", "滚动角", "透过率", "耐磨性", "功率保持率"],
                expected_outputs=["开题技术路线", "涂层样品", "性能测试数据", "论文实验章节"],
                domain_profile={
                    "material_route": "design-preparation-characterization-testing-mechanism",
                    "test_types": ["wettability", "optical", "durability", "PV performance"],
                },
            ),
            "reader_question": "该课题如何从涂层设计走向光伏应用价值验证？",
            "reader_path": ["研究目标", "研究内容", "关键技术", "实验验证", "预期成果"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "document", "description": "Chinese thesis proposal demo brief"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("objective", "研究目标", 1, "明确光伏盖板自清洁涂层的研究目标。", [
                    node("objective_problem", "降低表面污染", "针对灰尘、水滴和结冰导致的光伏盖板污染问题。", "objective", path, "Research problem"),
                    node("objective_value", "保护透光效率", "兼顾表面防护、透光性和发电收益相关性。", "objective", path, "PV value"),
                ]),
                stage("content", "研究内容", 2, "把研究任务拆分为材料、结构和性能三类内容。", [
                    node("content_material", "筛选涂层体系", "选择低表面能组分和适配光伏玻璃的基体材料。", "method", path, "Material selection"),
                    node("content_texture", "构筑微纳结构", "设计表面粗糙度和微纳结构以增强疏水与去污能力。", "method", path, "Texture design"),
                    node("content_process", "设计制备工艺", "比较喷涂、浸涂或溶胶凝胶等可放大工艺。", "implementation", path, "Process route"),
                ]),
                stage("technology", "关键技术", 3, "解决涂层性能背后的技术约束。", [
                    node("technology_wetting", "调控润湿行为", "利用接触角和滚动角指导表面结构设计。", "method", path, "Wetting behavior"),
                    node("technology_durability", "提升服役耐久性", "评估磨耗、紫外、湿热和热循环条件下的稳定性。", "validation", path, "Durability design"),
                    node("technology_transparency", "保持高透光率", "控制粗糙度和膜厚，避免引入明显光学损失。", "validation", path, "Transparency constraint"),
                ]),
                stage("validation", "实验验证", 4, "验证涂层功能和光伏应用相关性。", [
                    node("validation_surface", "表征表面结构", "利用形貌和化学表征确认涂层形成机制。", "validation", path, "Surface characterization"),
                    node("validation_cleaning", "测试自清洁功能", "比较除尘、排水、抗冰和污染恢复表现。", "validation", path, "Function tests"),
                    node("validation_power", "测量发电影响", "跟踪污染前后透过率和组件功率变化。", "validation", path, "PV performance"),
                ]),
                stage("outcome", "预期成果", 5, "把实验结果转化为可答辩的成果。", [
                    node("outcome_route", "形成技术路线", "建立从材料设计到光伏验证的完整研究路线。", "output", path, "Technical route"),
                    node("outcome_thesis", "支撑论文写作", "对应背景、方法、实验、结果和讨论章节。", "output", path, "Thesis output"),
                ]),
            ],
            "edges": [
                edge("e1", "objective_problem", "objective_value", "明确价值"),
                edge("e2", "objective_value", "content_material", "指导设计"),
                edge("e3", "content_material", "content_texture", "构筑结构"),
                edge("e4", "content_texture", "content_process", "形成工艺"),
                edge("e5", "content_process", "technology_wetting", "评价润湿"),
                edge("e6", "technology_wetting", "technology_durability", "平衡耐久"),
                edge("e7", "technology_durability", "technology_transparency", "约束透光"),
                edge("e8", "technology_transparency", "validation_surface", "开展表征"),
                edge("e9", "validation_surface", "validation_cleaning", "验证功能"),
                edge("e10", "validation_cleaning", "validation_power", "关联应用"),
                edge("e11", "validation_power", "outcome_route", "支撑路线"),
                edge("e12", "outcome_route", "outcome_thesis", "写入论文"),
            ],
        }
    )


def grant_route_cn():
    path = "examples/chinese-grant-application-demo/brief.md"
    return finalize(
        {
            "title": "智能光伏缺陷诊断项目申请技术路线图",
            "subtitle": "中文项目申请示例：研究内容、科学问题、关键方法与验证输出",
            "selected_preset": "chinese-grant-application",
            "layout": "cn-grant-application-route",
            "style": "cn-soft-grant-report",
            "domain_context": domain_context(
                discipline="计算机科学与新能源运维",
                subfield="光伏组件智能缺陷诊断",
                project_type="项目申请技术路线图",
                research_object="光伏组件多源缺陷与运维风险",
                method_family="多模态诊断、可解释评分与闭环优化",
                application_area="光伏电站智能巡检与运维决策",
                data_or_materials=["可见光图像", "红外图像", "电性能记录", "现场运维记录"],
                technical_objects=["多源样本库", "诊断模型", "风险评分", "人工复核", "闭环优化"],
                domain_constraints=["跨场景泛化", "诊断可信度", "运维可解释性", "样本持续更新"],
                evaluation_metrics=["准确率", "召回率", "误报率", "推理速度", "跨场景稳定性"],
                expected_outputs=["项目申请路线", "样本库", "原型系统", "诊断报告"],
                domain_profile={
                    "task_type": "multimodal diagnosis",
                    "data_modalities": ["RGB", "infrared", "electrical records", "maintenance records"],
                    "model_family": ["feature fusion", "explainable scoring", "closed-loop learning"],
                },
            ),
            "reader_question": "项目如何把科学问题、研究内容、关键方法和验证成果对应起来？",
            "reader_path": ["项目目标", "研究内容", "科学问题", "关键方法", "验证输出"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "document", "description": "Chinese grant application demo brief"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("objective", "项目目标", 1, "明确项目拟解决的问题和总体目标。", [
                    node("objective_need", "面向运维诊断需求", "聚焦光伏组件缺陷早期识别、风险分级和维护决策。", "objective", path, "Project need"),
                    node("objective_goal", "建立智能诊断框架", "构建从多源数据到可解释诊断结果的技术体系。", "objective", path, "Project goal"),
                ]),
                stage("content", "研究内容", 2, "把申请书研究内容拆分为可执行任务。", [
                    node("content_data", "构建多源样本库", "整合可见光、红外、电性能和现场运维记录。", "input", path, "Dataset construction"),
                    node("content_model", "研究诊断模型", "建立缺陷识别、风险评分和跨场景泛化模型。", "method", path, "Diagnostic model"),
                    node("content_platform", "设计应用流程", "形成采集、识别、复核、报告和反馈闭环。", "implementation", path, "Application workflow"),
                ]),
                stage("question", "科学问题", 3, "明确方法创新需要回答的核心问题。", [
                    node("question_feature", "弱纹理缺陷如何表征", "解决低对比、小尺度和热异常缺陷难以稳定表达的问题。", "method", path, "Feature question"),
                    node("question_general", "跨场景如何泛化", "处理不同组件类型、拍摄条件和气候环境造成的域差异。", "method", path, "Generalization question"),
                    node("question_trust", "诊断结果如何可信", "把模型输出与证据、置信度和人工复核逻辑连接起来。", "validation", path, "Trust question"),
                ]),
                stage("method", "关键方法", 4, "形成可验证的技术方案。", [
                    node("method_fusion", "多模态融合建模", "融合图像、电性能和运维特征，提高缺陷识别鲁棒性。", "method", path, "Multimodal fusion"),
                    node("method_explain", "可解释风险评分", "输出缺陷依据、影响因素和风险等级，服务运维决策。", "method", path, "Explainable scoring"),
                    node("method_loop", "闭环优化机制", "利用复核结果和新增样本持续修正诊断模型。", "feedback", path, "Closed-loop optimization"),
                ]),
                stage("validation", "验证输出", 5, "把项目成果转化为申请书可交付内容。", [
                    node("validation_metrics", "完成指标验证", "比较准确率、召回率、误报率、推理速度和跨场景稳定性。", "validation", path, "Metric validation"),
                    node("validation_demo", "形成原型系统", "输出样本库、模型、诊断报告和演示流程。", "output", path, "Prototype output"),
                ]),
            ],
            "edges": [
                edge("e1", "objective_need", "objective_goal", "提出目标"),
                edge("e2", "objective_goal", "content_data", "支撑内容"),
                edge("e3", "content_data", "content_model", "输入模型"),
                edge("e4", "content_model", "content_platform", "落地流程"),
                edge("e5", "content_platform", "question_feature", "提炼问题"),
                edge("e6", "question_feature", "question_general", "扩展场景"),
                edge("e7", "question_general", "question_trust", "要求可信"),
                edge("e8", "question_trust", "method_fusion", "设计方法"),
                edge("e9", "method_fusion", "method_explain", "解释结果"),
                edge("e10", "method_explain", "method_loop", "闭环优化"),
                edge("e11", "method_loop", "validation_metrics", "验证"),
                edge("e12", "validation_metrics", "validation_demo", "交付"),
            ],
        }
    )


def energy_route_cn():
    path = "examples/engineering-energy-system-demo/brief.md"
    return finalize(
        {
            "title": "校园综合能源系统源网荷储配置技术路线",
            "subtitle": "基于资源评估、容量测算、系统建模、仿真优化与结果评价的研究流程",
            "selected_preset": "engineering-project-report-cn",
            "layout": "cn-ppt-mainline-route",
            "style": "research-ppt-blue",
            "final_output": "形成校园综合能源系统源网荷储配置方案与运行优化分析结果",
            "domain_context": domain_context(
                discipline="能源工程",
                subfield="校园综合能源系统规划",
                project_type="工程项目汇报技术路线图",
                research_object="校园源网荷储一体化系统",
                method_family="系统建模、容量优化、运行仿真与情景验证",
                application_area="校园低碳能源规划与运行管理",
                data_or_materials=["电负荷曲线", "冷/热负荷曲线", "气象数据", "电价数据", "设备参数"],
                technical_objects=["光伏", "储能", "电网交互", "热泵", "调度策略", "KPI评价"],
                domain_constraints=["并网约束", "设备容量", "天气不确定性", "投资预算", "实施顺序"],
                evaluation_metrics=["运行成本", "碳排放", "新能源消纳率", "削峰效果", "可靠性"],
                expected_outputs=["容量配置方案", "运行策略", "情景对比", "工程交付文件"],
                domain_profile={
                    "system_scope": "source-grid-load-storage",
                    "analysis_types": ["planning optimization", "dispatch simulation", "sensitivity analysis"],
                },
            ),
            "reader_question": "工程路线如何把校园负荷证据转化为可验证的源网荷储配置方案？",
            "reader_path": ["基础数据", "容量配置", "系统建模", "仿真优化", "结果评价"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "engineering",
                "source_files": [{"path": path, "kind": "document", "description": "Chinese engineering energy system demo brief"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "engineering",
                "final_output": "形成校园综合能源系统源网荷储配置方案与运行优化分析结果",
                "demo": True,
            },
            "stages": [
                stage("boundary", "基础数据分析", 1, "明确校园综合能源项目边界和目标。", [
                    node("boundary_scope", "校园负荷特性", "识别建筑、负荷、能源资产和并网范围。", "objective", path, "Load characteristics"),
                    node("boundary_targets", "光伏资源条件", "平衡成本、碳减排、可靠性和新能源消纳。", "objective", path, "PV resource conditions"),
                    node("boundary_area", "可利用面积统计", "统计屋顶、车棚和空地等可布置光伏区域。", "input", path, "Available area"),
                ]),
                stage("data", "容量配置计算", 2, "建立配置优化的基础证据。", [
                    node("data_load", "装机容量估算", "形成逐时电、热、冷和可调负荷曲线。", "input", path, "Capacity estimate"),
                    node("data_resource", "组件数量核算", "估算光伏、储能、屋顶面积和可用资源。", "input", path, "Module quantity"),
                    node("data_tariff", "理论发电量计算", "纳入电价、需量、电网交互和碳排因子约束。", "input", path, "Power generation"),
                ]),
                stage("model", "系统结构建模", 3, "优化源网荷储容量和运行边界。", [
                    node("model_assets", "源网荷储拓扑", "表达光伏、储能、热泵、购电和可调负荷等设备。", "method", path, "System topology"),
                    node("model_objective", "并网接入方式", "在成本、碳排和可靠性之间求解配置方案。", "method", path, "Grid connection"),
                    node("model_scenarios", "EMS 控制结构", "比较基准、低碳优先、储能优先和经济优先场景。", "validation", path, "EMS structure"),
                ]),
                stage("operation", "运行仿真优化", 4, "把规划结果转化为运行逻辑。", [
                    node("operation_dispatch", "典型日出力", "协调光伏自用、储能充放电和电网交互。", "implementation", path, "Typical-day output"),
                    node("operation_control", "源荷匹配分析", "区分日前计划、日内修正和实时控制。", "implementation", path, "Source-load matching"),
                    node("operation_storage", "储能充放电策略", "分析储能在削峰、消纳和经济运行中的调节作用。", "implementation", path, "Storage strategy"),
                ]),
                stage("validation", "结果评价应用", 5, "验证工程可行性并形成交付物。", [
                    node("validation_kpi", "运行效果评价", "输出成本、碳排、新能源消纳、削峰和可靠性指标。", "validation", path, "Operation evaluation"),
                    node("validation_sensitivity", "配置方案优化", "测试电价、天气、负荷增长和设备成本不确定性。", "validation", path, "Configuration optimization"),
                    node("validation_deliver", "工程应用建议", "形成容量配置、运行策略、风险提示和实施顺序。", "output", path, "Engineering suggestion"),
                ]),
            ],
            "edges": [
                edge("e1", "boundary_scope", "boundary_targets", "设定目标"),
                edge("e2", "boundary_targets", "boundary_area", "统计面积"),
                edge("e3", "boundary_area", "data_load", "估算容量"),
                edge("e4", "data_load", "data_resource", "核算组件"),
                edge("e5", "data_resource", "data_tariff", "计算发电量"),
                edge("e6", "data_tariff", "model_assets", "输入模型"),
                edge("e7", "model_assets", "model_objective", "接入电网"),
                edge("e8", "model_objective", "model_scenarios", "控制结构"),
                edge("e9", "model_scenarios", "operation_dispatch", "仿真出力"),
                edge("e10", "operation_dispatch", "operation_control", "匹配源荷"),
                edge("e11", "operation_control", "operation_storage", "储能调节"),
                edge("e12", "operation_storage", "validation_kpi", "评价效果"),
                edge("e13", "validation_kpi", "validation_sensitivity", "优化方案"),
                edge("e14", "validation_sensitivity", "validation_deliver", "输出建议"),
            ],
        }
    )


def biomedical_route_cn():
    path = "examples/biomedical-mechanism-demo/brief.md"
    return finalize(
        {
            "title": "炎症微环境调控骨修复机制研究技术路线图",
            "subtitle": "生物医学机制研究示例：样本模型、干预检测、机制验证与转化意义",
            "selected_preset": "chinese-thesis-proposal",
            "layout": "cn-a4-stage-route",
            "style": "research-ppt-blue",
            "domain_context": domain_context(
                discipline="生物医学",
                subfield="炎症微环境与骨组织修复机制",
                project_type="课题申报/论文机制研究技术路线图",
                research_object="炎症微环境下成骨分化与骨缺损修复过程",
                method_family="样本模型、分组干预、分子检测与机制验证",
                application_area="骨缺损修复与再生医学研究",
                data_or_materials=["细胞模型", "动物骨缺损模型", "炎症因子处理样本", "组织切片", "分子检测数据"],
                technical_objects=["实验分组", "成骨指标", "炎症因子", "信号通路", "组织学验证"],
                domain_constraints=["伦理审批", "样本量", "批次差异", "阳性/阴性对照", "统计显著性"],
                evaluation_metrics=["ALP活性", "矿化结节", "炎症因子表达", "骨量参数", "p值与效应量"],
                expected_outputs=["机制路线图", "实验验证结果", "候选靶点", "论文图表"],
                domain_profile={
                    "study_type": "biomedical mechanism validation",
                    "sample_design": ["cell model", "animal model", "tissue validation"],
                    "validation_types": ["assay", "molecular detection", "histology", "statistics"],
                },
            ),
            "reader_question": "该研究如何从炎症表型走向骨修复机制验证与转化意义？",
            "reader_path": ["研究问题", "模型构建", "分组干预", "机制检测", "验证输出"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "document", "description": "Biomedical mechanism demo brief"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("question", "研究问题", 1, "明确炎症微环境影响骨修复的核心科学问题。", [
                    node("question_inflammation", "界定炎症表型", "识别炎症因子变化与骨修复受阻之间的关系。", "objective", path, "Inflammation phenotype"),
                    node("question_mechanism", "提出机制假设", "假设特定信号通路调控成骨分化与组织修复。", "objective", path, "Mechanism hypothesis"),
                ]),
                stage("model", "模型构建", 2, "建立细胞与动物层面的验证对象。", [
                    node("model_cell", "建立细胞模型", "构建炎症刺激下的成骨细胞或干细胞分化模型。", "input", path, "Cell model"),
                    node("model_animal", "建立缺损模型", "构建标准化骨缺损动物模型用于组织修复验证。", "input", path, "Animal model"),
                    node("model_control", "设置对照组", "设置空白、模型、干预和阳性对照以保证可比性。", "validation", path, "Control groups"),
                ]),
                stage("intervention", "分组干预", 3, "把机制假设转化为可检验的实验处理。", [
                    node("intervention_factor", "调控炎症因子", "通过因子刺激、抑制剂或基因干预改变炎症状态。", "method", path, "Inflammatory intervention"),
                    node("intervention_pathway", "干预信号通路", "围绕候选通路进行激活、抑制或表达调控。", "method", path, "Pathway intervention"),
                ]),
                stage("assay", "机制检测", 4, "用多层证据验证成骨、炎症和通路变化。", [
                    node("assay_osteogenesis", "检测成骨指标", "检测ALP、矿化结节、成骨相关基因和蛋白表达。", "validation", path, "Osteogenesis assays"),
                    node("assay_inflammation", "检测炎症表达", "检测炎症因子、免疫标志物和微环境变化。", "validation", path, "Inflammation assays"),
                    node("assay_histology", "开展组织学验证", "利用组织染色和骨量参数验证体内修复效果。", "validation", path, "Histology validation"),
                ]),
                stage("output", "验证输出", 5, "形成可写入论文或申报书的机制链条。", [
                    node("output_mechanism", "形成机制链条", "连接炎症状态、通路调控、成骨变化和修复结果。", "output", path, "Mechanism chain"),
                    node("output_target", "筛选干预靶点", "提出可进一步验证的候选靶点或治疗策略。", "output", path, "Candidate target"),
                ]),
            ],
            "edges": [
                edge("e1", "question_inflammation", "question_mechanism", "提出假设"),
                edge("e2", "question_mechanism", "model_cell", "指导建模"),
                edge("e3", "model_cell", "model_animal", "扩展验证"),
                edge("e4", "model_animal", "model_control", "设置对照"),
                edge("e5", "model_control", "intervention_factor", "进入干预"),
                edge("e6", "intervention_factor", "intervention_pathway", "验证通路"),
                edge("e7", "intervention_pathway", "assay_osteogenesis", "检测成骨"),
                edge("e8", "assay_osteogenesis", "assay_inflammation", "关联炎症"),
                edge("e9", "assay_inflammation", "assay_histology", "体内验证"),
                edge("e10", "assay_histology", "output_mechanism", "支持机制"),
                edge("e11", "output_mechanism", "output_target", "凝练靶点"),
            ],
        }
    )


def drawio_copy_code_route_cn():
    path = "examples/drawio-copy-code-demo/source/hgdy-route-reference-cropped.png"
    return finalize(
        {
            "title": "HGDY光催化降解木质素技术路线图",
            "subtitle": "Draw.io复制代码示例：从技术路线图参考图生成可编辑Draw.io XML",
            "selected_preset": "chinese-grant-application",
            "layout": "cn-grant-application-route",
            "style": "cn-soft-grant-report",
            "domain_context": domain_context(
                discipline="材料科学与化学工程",
                subfield="光催化降解木质素与石墨炔基催化材料",
                project_type="大学生创新创业训练项目技术路线图",
                research_object="棉秆废弃物木质素高值化利用与HGDY光催化体系",
                method_family="文献调研、材料合成、仪器表征、色谱分析与综合评价",
                application_area="农业废弃物资源化与木质素绿色转化",
                data_or_materials=["棉秆废弃物木质素", "HGDY催化剂", "模型底物", "光催化反应样品", "HPLC检测数据"],
                technical_objects=["项目立项", "材料制备", "性能表征", "实验机理", "优化应用"],
                domain_constraints=["C-C键断裂限制", "催化剂结构稳定性", "光生载流子迁移", "实际生物质适用性"],
                evaluation_metrics=["单体转化率", "HPLC路径", "光电性能", "循环降解活性保持率", "推广价值"],
                expected_outputs=["可复制Draw.io XML代码", "可编辑Draw.io路线图", "项目申请书技术路线图", "优化评价方案"],
                domain_profile={
                    "route_style": "drawio-copy-code-demo",
                    "reference_image": path,
                    "drawio_url": "https://app.diagrams.net/",
                },
            ),
            "reader_question": "该示例如何把HGDY光催化降解木质素项目路线转化为可复制到Draw.io的XML代码？",
            "reader_path": ["提出问题", "材料制备", "性能表征", "机理探究", "优化评价"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "drawio-code", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "image", "description": "User-provided Draw.io technical route reference image"}],
                "source_hashes": [],
                "language": "zh-CN",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("proposal", "项目立项", 1, "从木质素高值化利用与关键键断裂限制提出研究问题。", [
                    node("proposal_value", "棉秆木质素高值化利用", "围绕新疆棉秆废弃物木质素资源化利用提出项目方向。", "objective", path, "研究内容：新疆棉秆废弃物木质素的高值化利用"),
                    node("proposal_cc", "突破C-C键断裂限制", "聚焦木质素顽固C-C键断裂的热力学限制。", "objective", path, "研究内容：突破木质素顽固C-C键断裂的热力学限制"),
                    node("proposal_hgdy", "构建HGDY催化体系", "设计氢取代石墨炔催化剂体系支撑光催化转化。", "method", path, "研究内容：构建氢取代石墨炔（HGDY）催化剂体系设计"),
                ]),
                stage("material", "材料制备", 2, "制备并调控HGDY材料结构。", [
                    node("material_synthesis", "HGDY单体可控合成", "开展HGDY单体可控合成，形成后续性能测试样品。", "implementation", path, "研究内容：HGDY单体的可控合成"),
                    node("material_tuning", "带隙和形貌精准调控", "调控HGDY带隙与形貌，为光催化性能优化提供结构基础。", "implementation", path, "研究内容：HGDY带隙和形貌的精准调控"),
                ]),
                stage("characterization", "性能表征", 3, "用多类仪器表征结构、形貌、界面与光电性能。", [
                    node("characterization_phase", "物相与化学结构表征", "通过XRD、FTIR、XPS确认物相与化学结构。", "validation", path, "研究内容：物相与化学结构表征（XRD/FTIR/XPS）"),
                    node("characterization_micro", "形貌与元素分布", "通过SEM、TEM、EDS分析微观形貌与界面元素分布。", "validation", path, "研究内容：微观形貌与界面元素分布（SEM/TEM/EDS）"),
                    node("characterization_photo", "光电性能与能带结构", "通过UV-Vis、PL、EIS、Mott-Schottky评价光电性能与能带结构。", "validation", path, "研究内容：光电性能与能带结构（UV-Vis/PL/EIS/Mott-Schottky）"),
                ]),
                stage("mechanism", "实验机理", 4, "从性能测试、路径推测和自由基捕获验证降解机理。", [
                    node("mechanism_activity", "降解性能与转化率评价", "开展模型体系降解性能测试与单体转化率评价。", "validation", path, "研究内容：模型体系降解性能测试与单体转化率评价"),
                    node("mechanism_hplc", "HPLC路径推测", "基于PCET-SCS级联机制推测降解机理与HPLC路径。", "method", path, "研究内容：基于PCET-SCS级联的降解机理与HPLC路径推测"),
                    node("mechanism_radical", "自由基与载流子验证", "用自由基淬灭捕获和光生载流子迁移验证机理链条。", "validation", path, "研究内容：自由基淬灭捕获与光生载流子迁移验证"),
                ]),
                stage("application", "优化应用", 5, "优化反应条件并评价应用潜力。", [
                    node("application_conversion", "优化转化率条件", "调控前驱体比例、氧气含量等因素优化转化率。", "implementation", path, "研究内容：通过调控前驱体比例、氧气含量等优化转化率"),
                    node("application_stability", "循环稳定性监测", "监测结构稳定性与多次循环降解活性保持率。", "validation", path, "研究内容：结构稳定性监测与多次循环降解活性保持率"),
                    node("application_value", "应用潜力与推广评价", "评价实际生物质降解应用潜力与推广价值。", "output", path, "研究内容：实际生物质降解应用潜力与推广价值评价"),
                ]),
            ],
            "edges": [
                edge("e1", "proposal_value", "proposal_cc", "提出关键限制"),
                edge("e2", "proposal_cc", "proposal_hgdy", "设计催化体系"),
                edge("e3", "proposal_hgdy", "material_synthesis", "进入制备"),
                edge("e4", "material_synthesis", "material_tuning", "调控结构"),
                edge("e5", "material_tuning", "characterization_phase", "表征物相"),
                edge("e6", "characterization_phase", "characterization_micro", "观察形貌"),
                edge("e7", "characterization_micro", "characterization_photo", "评估光电"),
                edge("e8", "characterization_photo", "mechanism_activity", "测试性能"),
                edge("e9", "mechanism_activity", "mechanism_hplc", "推测路径"),
                edge("e10", "mechanism_hplc", "mechanism_radical", "验证机理"),
                edge("e11", "mechanism_radical", "application_conversion", "优化条件"),
                edge("e12", "application_conversion", "application_stability", "评估稳定"),
                edge("e13", "application_stability", "application_value", "形成应用评价"),
            ],
        }
    )


DEMOS = {
    "academic-paper-demo": (academic_route_cn, "Chinese academic paper demo brief for a PV surface defect detection method route."),
    "thesis-proposal-demo": (thesis_route_cn, "Chinese thesis proposal demo brief for PV self-cleaning coating research."),
    "chinese-grant-application-demo": (grant_route_cn, "Chinese grant application demo brief for intelligent PV defect diagnosis."),
    "engineering-energy-system-demo": (energy_route_cn, "Chinese engineering demo brief for a campus source-grid-load-storage energy system."),
    "biomedical-mechanism-demo": (biomedical_route_cn, "Chinese biomedical mechanism demo brief for inflammation microenvironment and bone repair."),
    "drawio-copy-code-demo": (drawio_copy_code_route_cn, "Draw.io copy-code demo brief based on an HGDY lignin photocatalysis technical route."),
    "agent-workflow-demo": (workflow_route, "Workflow demo brief for converting technical materials into editable route diagrams."),
    "legacy-campaign-route-demo": (campaign_route, "Legacy campaign demo brief retained only for explicit advertising requests."),
}


def write_brief(folder, text):
    target = ROOT / "examples" / folder / "brief.md"
    write_text(target, f"# {folder}\n\n{text}\n")


def render_demo(folder, route_factory):
    example_dir = ROOT / "examples" / folder
    out_dir = example_dir / "outputs"
    out_dir.mkdir(parents=True, exist_ok=True)
    route = route_factory()
    route_path = out_dir / "tech-route.json"
    write_text(route_path, json.dumps(route, ensure_ascii=False, indent=2) + "\n")
    subprocess.check_call([
        sys.executable,
        str(ROOT / "scripts" / "render_all.py"),
        str(route_path),
        str(out_dir),
        "--formats",
        CORE_FORMATS,
    ])


def svg_text(x, y, value, size, color, weight=400, anchor="middle"):
    return f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-family="Arial, Helvetica, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(value)}</text>'


def svg_rect(x, y, w, h, fill, stroke="#D7E0EA", rx=10, width=1.3):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>'


def asset_svg(width, height, compact=False):
    cards = [
        ("Paper Matrix", "#E4F3F1", "#2F7CA6", ["Goal", "Data", "Method", "Validation"]),
        ("Proposal Poster", "#F8E3EA", "#64C7C8", ["Objective", "Content", "Technology", "Output"]),
        ("Grant Route", "#F4EDE3", "#4E7FB0", ["Problem", "Questions", "Methods", "Deliverables"]),
        ("Engineering Map", "#E7F0F7", "#5E9F3B", ["Boundary", "Resources", "Model", "KPIs"]),
    ]
    title = "tech-route-maker" if compact else "Editable Research Route Templates"
    subtitle = "Chinese academic presets, editable PPTX/SVG/Draw.io outputs, and source-grounded quality reports"
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
        svg_rect(18, 18, width - 36, height - 36, "#FFFFFF", "#D8E1EA", 18, 1),
        svg_text(width // 2, 66 if compact else 82, title, 30 if compact else 38, "#172033", 700),
        svg_text(width // 2, 104 if compact else 124, subtitle, 15 if compact else 17, "#59636A", 400),
    ]
    start_x = 66
    card_y = 146 if compact else 190
    card_w = 250 if compact else 270
    card_h = 164 if compact else 360
    gap = 28 if compact else 32
    for i, (name, fill, accent, labels) in enumerate(cards):
        x = start_x + i * (card_w + gap)
        out.append(svg_rect(x, card_y, card_w, card_h, fill, "#C8D4E0", 14, 1.4))
        out.append(svg_rect(x + 18, card_y + 18, card_w - 36, 32, accent, accent, 8, 1))
        out.append(svg_text(x + card_w / 2, card_y + 39, name, 14, "#FFFFFF", 700))
        visible = labels[:3] if compact else labels
        for j, label in enumerate(visible):
            y = card_y + 68 + j * (34 if compact else 58)
            h = 24 if compact else 38
            out.append(svg_rect(x + 30, y, card_w - 60, h, "#FFFFFF", "#9DB3C5", 7, 1.1))
            out.append(svg_text(x + card_w / 2, y + h / 2 + 4, label, 11 if compact else 14, "#172033", 600))
            if j < len(visible) - 1:
                cx = x + card_w / 2
                out.append(f'<path d="M {cx} {y + h} L {cx} {y + (34 if compact else 58) - 2}" stroke="{accent}" stroke-width="1.6" marker-end="url(#arrow{i})"/>')
        out.append(f'<defs><marker id="arrow{i}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{accent}"/></marker></defs>')
    out.append(svg_text(width // 2, height - (24 if compact else 42), "Editable PPTX shapes | SVG vectors | Draw.io cells | HTML evidence preview", 13 if compact else 15, "#59636A", 600))
    out.append("</svg>")
    return "\n".join(out)


def write_assets():
    assets = ROOT / "assets"
    assets.mkdir(exist_ok=True)
    write_text(assets / "banner.svg", asset_svg(1280, 360, compact=True))
    write_text(assets / "demo-preview.svg", asset_svg(1280, 720, compact=False))
    write_text(assets / "social-preview.svg", asset_svg(1200, 630, compact=False))


def main():
    for folder, (factory, brief) in DEMOS.items():
        write_brief(folder, brief)
        render_demo(folder, factory)
    sample = ROOT / "examples" / "sample-tech-route.json"
    write_text(sample, json.dumps(academic_route(), ensure_ascii=False, indent=2) + "\n")
    write_assets()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
