import json
import subprocess
import sys
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tech_route_maker.quality import build_quality_report  # noqa: E402


CORE_FORMATS = "pptx,svg,drawio,excalidraw,mermaid,html,markdown,json"


def write_text(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def ev(path, note):
    return [
        {
            "kind": "source",
            "source_id": "source_1",
            "path": path,
            "locator": note,
            "quote_or_note": note,
        }
    ]


def node(node_id, label, detail, tag, path, note, confidence="high"):
    return {
        "id": node_id,
        "label": label,
        "detail": detail,
        "tag": tag,
        "node_type": tag,
        "confidence": confidence,
        "is_inferred": False,
        "evidence": ev(path, note),
    }


def stage(stage_id, title, order, summary, nodes):
    return {"id": stage_id, "title": title, "order": order, "summary": summary, "nodes": nodes}


def edge(edge_id, source, target, label, kind="flow", confidence="medium"):
    return {"id": edge_id, "from": source, "to": target, "label": label, "kind": kind, "confidence": confidence, "evidence": []}


def finalize(route):
    route.setdefault("route_version", "0.2.0")
    route.setdefault("assumptions", [])
    route.setdefault("unresolved_questions", [])
    route.setdefault("citations", [])
    route.setdefault("renderer_overrides", {})
    route["quality_report"] = build_quality_report(route)
    return route


def academic_route():
    path = "examples/academic-paper-demo/brief.md"
    return finalize(
        {
            "title": "PV Surface Defect Detection Method Route",
            "subtitle": "Academic method framework demo generated by tech-route-maker",
            "selected_preset": "academic-method",
            "layout": "academic-method-framework",
            "style": "academic-blue",
            "reader_question": "How does the method move from multi-source image evidence to validated defect results?",
            "reader_path": ["Goal", "Data", "Method", "Training", "Validation", "Output"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "paper",
                "source_files": [{"path": path, "kind": "document", "description": "Academic paper demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("goal", "Research Goal", 1, "Define the detection task and evaluation target.", [
                    node("goal_task", "Define defect task", "Identify visible and thermal defect categories in PV module images.", "objective", path, "Detection task"),
                    node("goal_metric", "Set evaluation metrics", "Use precision, recall, mAP, inference speed, and failure cases as evaluation anchors.", "objective", path, "Evaluation metrics"),
                ]),
                stage("data", "Data Evidence", 2, "Build traceable RGB and infrared image evidence.", [
                    node("data_collect", "Collect RGB and IR images", "Gather complementary visible and infrared image evidence.", "input", path, "Multimodal images"),
                    node("data_align", "Align and annotate defects", "Register image pairs and label defect locations or classes.", "input", path, "Alignment and annotation"),
                    node("data_split", "Prepare train test sets", "Clean low-quality samples and split training, validation, and test data.", "implementation", path, "Dataset split"),
                ]),
                stage("method", "Method Design", 3, "Convert evidence into a defect detection model.", [
                    node("method_baseline", "Build baseline detector", "Start from a general object detector as the controlled baseline.", "method", path, "Baseline detector"),
                    node("method_fusion", "Fuse multimodal features", "Combine RGB and infrared features for stronger defect representation.", "method", path, "Feature fusion"),
                    node("method_attention", "Enhance weak regions", "Use feature enhancement to emphasize weak-texture or small defect regions.", "method", path, "Region enhancement"),
                ]),
                stage("training", "Training Validation", 4, "Train and check whether each design choice contributes.", [
                    node("training_loss", "Optimize detection losses", "Balance classification, localization, and confidence losses.", "implementation", path, "Loss optimization"),
                    node("training_ablation", "Run ablation studies", "Verify fusion, enhancement, and training strategy contributions.", "validation", path, "Ablation plan"),
                    node("training_infer", "Infer defect candidates", "Run inference and filter candidates by confidence.", "implementation", path, "Inference plan"),
                ]),
                stage("output", "Validation Output", 5, "Connect model results to paper-ready evidence.", [
                    node("output_metrics", "Report quantitative gains", "Compare against baselines with mAP, precision, recall, and speed.", "validation", path, "Metric report"),
                    node("output_visual", "Explain visual results", "Show detections, heat responses, and failure cases for interpretability.", "output", path, "Visual explanation"),
                    node("output_report", "Generate defect report", "Summarize defect class, location, confidence, and maintenance priority.", "output", path, "Defect report"),
                ]),
            ],
            "edges": [
                edge("e1", "goal_task", "goal_metric", "defines"),
                edge("e2", "goal_metric", "data_collect", "guides"),
                edge("e3", "data_collect", "data_align", "aligns"),
                edge("e4", "data_align", "data_split", "prepares"),
                edge("e5", "data_split", "method_baseline", "feeds"),
                edge("e6", "method_baseline", "method_fusion", "extends"),
                edge("e7", "method_fusion", "method_attention", "enhances"),
                edge("e8", "method_attention", "training_loss", "optimizes"),
                edge("e9", "training_loss", "training_ablation", "tests"),
                edge("e10", "training_ablation", "training_infer", "selects"),
                edge("e11", "training_infer", "output_metrics", "evaluates"),
                edge("e12", "output_metrics", "output_visual", "explains"),
                edge("e13", "output_visual", "output_report", "reports"),
            ],
        }
    )


def thesis_route():
    path = "examples/thesis-proposal-demo/brief.md"
    return finalize(
        {
            "title": "Photovoltaic Self-Cleaning Coating Proposal Route",
            "subtitle": "Thesis proposal technical route generated by tech-route-maker",
            "selected_preset": "thesis-proposal",
            "layout": "proposal-matrix-route",
            "style": "presentation-clean",
            "reader_question": "How does the proposal connect coating design, performance testing, and PV application value?",
            "reader_path": ["Objective", "Research Content", "Key Technology", "Validation", "Expected Outcomes"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "proposal",
                "source_files": [{"path": path, "kind": "document", "description": "Thesis proposal demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "research",
                "demo": True,
            },
            "stages": [
                stage("objective", "Research Objective", 1, "Define the PV self-cleaning coating research target.", [
                    node("objective_problem", "Reduce surface contamination", "Address dust, water, and ice accumulation on PV cover glass.", "objective", path, "Research problem"),
                    node("objective_value", "Protect optical efficiency", "Balance surface protection with transparency and energy-yield relevance.", "objective", path, "PV value"),
                ]),
                stage("content", "Research Content", 2, "Organize the proposal into material, structure, and performance content.", [
                    node("content_material", "Select coating chemistry", "Choose low-surface-energy chemistry and compatible matrix materials.", "method", path, "Material selection"),
                    node("content_texture", "Design micro nano texture", "Construct surface texture for hydrophobicity and contaminant removal.", "method", path, "Texture design"),
                    node("content_process", "Plan scalable process", "Compare spraying, dip-coating, or sol-gel routes for PV glass.", "implementation", path, "Process route"),
                ]),
                stage("technology", "Key Technology", 3, "Resolve the technical constraints behind coating performance.", [
                    node("technology_wettability", "Tune wetting behavior", "Use contact angle and sliding angle to guide surface design.", "method", path, "Wetting behavior"),
                    node("technology_durability", "Improve durability", "Evaluate abrasion, UV exposure, humidity, and thermal cycling.", "validation", path, "Durability design"),
                    node("technology_transparency", "Maintain transparency", "Control roughness and thickness to limit optical loss.", "validation", path, "Transparency constraint"),
                ]),
                stage("validation", "Experimental Validation", 4, "Verify coating function and PV relevance.", [
                    node("validation_surface", "Characterize surface structure", "Use morphology and chemical characterization to confirm coating formation.", "validation", path, "Surface characterization"),
                    node("validation_cleaning", "Test self-cleaning function", "Compare dust removal, water shedding, and icing behavior.", "validation", path, "Function tests"),
                    node("validation_power", "Measure PV impact", "Track transmittance and power output before and after contamination.", "validation", path, "PV performance"),
                ]),
                stage("outcome", "Expected Outcomes", 5, "Convert experiments into proposal deliverables.", [
                    node("outcome_route", "Form technical route", "Produce a defensible route from material design to PV performance validation.", "output", path, "Technical route"),
                    node("outcome_thesis", "Support thesis chapters", "Connect background, method, experiment, results, and discussion chapters.", "output", path, "Thesis output"),
                ]),
            ],
            "edges": [
                edge("e1", "objective_problem", "objective_value", "frames"),
                edge("e2", "objective_value", "content_material", "guides"),
                edge("e3", "content_material", "content_texture", "supports"),
                edge("e4", "content_texture", "content_process", "scales"),
                edge("e5", "content_process", "technology_wettability", "requires"),
                edge("e6", "technology_wettability", "technology_durability", "balances"),
                edge("e7", "technology_durability", "technology_transparency", "constrains"),
                edge("e8", "technology_transparency", "validation_surface", "checks"),
                edge("e9", "validation_surface", "validation_cleaning", "tests"),
                edge("e10", "validation_cleaning", "validation_power", "links"),
                edge("e11", "validation_power", "outcome_route", "supports"),
                edge("e12", "outcome_route", "outcome_thesis", "writes"),
            ],
        }
    )


def energy_route():
    path = "examples/engineering-energy-system-demo/brief.md"
    return finalize(
        {
            "title": "Campus Integrated Energy System Technical Route",
            "subtitle": "Source-grid-load-storage engineering route generated by tech-route-maker",
            "selected_preset": "engineering-system",
            "layout": "engineering-architecture-route",
            "style": "dark-technical",
            "reader_question": "How does the engineering route turn campus demand evidence into a validated source-grid-load-storage configuration?",
            "reader_path": ["Boundary", "Data", "Configuration", "Operation", "Validation", "Deliverables"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "engineering",
                "source_files": [{"path": path, "kind": "document", "description": "Engineering energy system demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "engineering",
                "demo": True,
            },
            "stages": [
                stage("boundary", "System Boundary", 1, "Define the campus energy boundary and objectives.", [
                    node("boundary_scope", "Define campus boundary", "Identify buildings, loads, energy assets, and grid connection scope.", "objective", path, "System boundary"),
                    node("boundary_targets", "Set planning targets", "Balance cost, carbon reduction, reliability, and renewable utilization.", "objective", path, "Planning targets"),
                ]),
                stage("data", "Source Load Data", 2, "Build the evidence base for configuration.", [
                    node("data_load", "Profile electric thermal load", "Construct hourly electricity, heating, cooling, and flexible load profiles.", "input", path, "Load profiles"),
                    node("data_resource", "Assess renewable resources", "Estimate solar, wind, storage, and available land or roof resources.", "input", path, "Resource assessment"),
                    node("data_tariff", "Collect tariff constraints", "Include tariff, demand charge, carbon factor, and grid interaction limits.", "input", path, "Tariff and constraints"),
                ]),
                stage("model", "Configuration Model", 3, "Optimize source-grid-load-storage sizing.", [
                    node("model_assets", "Model candidate assets", "Represent PV, storage, heat pump, grid purchase, and controllable loads.", "method", path, "Candidate assets"),
                    node("model_objective", "Optimize multi-objective sizing", "Solve cost-carbon-reliability tradeoffs under engineering constraints.", "method", path, "Optimization objective"),
                    node("model_scenarios", "Compare planning scenarios", "Run baseline, renewable-priority, storage-priority, and low-carbon scenarios.", "validation", path, "Scenario comparison"),
                ]),
                stage("operation", "Operation Strategy", 4, "Turn the planning result into operating logic.", [
                    node("operation_dispatch", "Build dispatch strategy", "Coordinate PV self-consumption, storage charge-discharge, and grid exchange.", "implementation", path, "Dispatch strategy"),
                    node("operation_control", "Define control hierarchy", "Separate day-ahead planning, intraday correction, and real-time control.", "implementation", path, "Control hierarchy"),
                ]),
                stage("validation", "Validation Output", 5, "Verify engineering feasibility and deliverables.", [
                    node("validation_kpi", "Evaluate system KPIs", "Report cost, carbon, renewable utilization, peak shaving, and reliability metrics.", "validation", path, "KPI evaluation"),
                    node("validation_sensitivity", "Run sensitivity checks", "Test tariff, weather, load growth, and equipment-cost uncertainty.", "validation", path, "Sensitivity analysis"),
                    node("validation_deliver", "Deliver configuration plan", "Output capacity plan, operation plan, risk notes, and implementation sequence.", "output", path, "Deliverables"),
                ]),
            ],
            "edges": [
                edge("e1", "boundary_scope", "boundary_targets", "sets"),
                edge("e2", "boundary_targets", "data_load", "requires"),
                edge("e3", "data_load", "data_resource", "combines"),
                edge("e4", "data_resource", "data_tariff", "constrains"),
                edge("e5", "data_tariff", "model_assets", "feeds"),
                edge("e6", "model_assets", "model_objective", "optimizes"),
                edge("e7", "model_objective", "model_scenarios", "compares"),
                edge("e8", "model_scenarios", "operation_dispatch", "selects"),
                edge("e9", "operation_dispatch", "operation_control", "organizes"),
                edge("e10", "operation_control", "validation_kpi", "validates"),
                edge("e11", "validation_kpi", "validation_sensitivity", "stress tests"),
                edge("e12", "validation_sensitivity", "validation_deliver", "delivers"),
            ],
        }
    )


def workflow_route():
    path = "examples/agent-workflow-demo/brief.md"
    return finalize(
        {
            "title": "Agent Workflow For Editable Route Diagrams",
            "subtitle": "Workflow pipeline demo generated by tech-route-maker",
            "selected_preset": "workflow-pipeline",
            "layout": "horizontal-stages",
            "style": "minimal-gray",
            "reader_question": "How does the agent convert technical source material into editable, reviewable route diagrams?",
            "reader_path": ["Source Intake", "Evidence Extraction", "Route JSON", "Editable Rendering", "Quality Review"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "workflow",
                "source_files": [{"path": path, "kind": "document", "description": "Agent workflow demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "technical",
                "demo": True,
            },
            "stages": [
                stage("intake", "Source Intake", 1, "Collect and scope the technical source material.", [
                    node("intake_scope", "Confirm source scope", "Use a repository, paper, proposal, brief, or pasted notes as the evidence boundary.", "input", path, "Source scope"),
                    node("intake_safety", "Avoid unsafe execution", "Read project files without running untrusted code unless the user approves.", "input", path, "Safety rule"),
                ]),
                stage("extract", "Evidence Extraction", 2, "Extract route elements from source evidence.", [
                    node("extract_objective", "Find objectives and gaps", "Identify the target problem, reader question, and expected result.", "method", path, "Objective extraction"),
                    node("extract_steps", "Extract method steps", "Collect non-droppable stages, modules, inputs, outputs, and validation logic.", "method", path, "Step extraction"),
                    node("extract_evidence", "Attach evidence notes", "Record source paths, locators, and notes for visible nodes.", "validation", path, "Evidence linking"),
                ]),
                stage("model", "Route JSON", 3, "Create an auditable source model before drawing.", [
                    node("model_schema", "Build route schema", "Write stages, nodes, edges, confidence, assumptions, and unresolved questions.", "implementation", path, "Schema build"),
                    node("model_validate", "Validate route model", "Check version, preset, evidence, edge endpoints, and label length.", "validation", path, "Validation"),
                ]),
                stage("render", "Editable Rendering", 4, "Render the same route into editable outputs.", [
                    node("render_pptx", "Render PPTX shapes", "Create PowerPoint-native shapes, text boxes, and connectors.", "output", path, "PPTX render"),
                    node("render_svg", "Render SVG vector", "Generate vector shapes and text for design-tool editing.", "output", path, "SVG render"),
                    node("render_drawio", "Render Draw.io cells", "Export editable diagrams.net nodes and edges for maintenance.", "output", path, "Draw.io render"),
                ]),
                stage("review", "Quality Review", 5, "Make warnings and manual revision needs visible.", [
                    node("review_report", "Generate quality report", "Summarize evidence coverage, inferred nodes, warnings, and manual review tasks.", "validation", path, "Quality report"),
                    node("review_iterate", "Revise editable files", "Let the user adjust wording, color, spacing, and route logic in editable outputs.", "feedback", path, "Iteration loop"),
                ]),
            ],
            "edges": [
                edge("e1", "intake_scope", "intake_safety", "bounds"),
                edge("e2", "intake_safety", "extract_objective", "starts"),
                edge("e3", "extract_objective", "extract_steps", "structures"),
                edge("e4", "extract_steps", "extract_evidence", "grounds"),
                edge("e5", "extract_evidence", "model_schema", "writes"),
                edge("e6", "model_schema", "model_validate", "checks"),
                edge("e7", "model_validate", "render_pptx", "renders"),
                edge("e8", "model_validate", "render_svg", "renders"),
                edge("e9", "model_validate", "render_drawio", "renders"),
                edge("e10", "render_pptx", "review_report", "reviews"),
                edge("e11", "review_report", "review_iterate", "improves"),
                edge("e12", "review_iterate", "model_schema", "updates", "feedback"),
            ],
        }
    )


def campaign_route():
    path = "examples/legacy-campaign-route-demo/brief.md"
    return finalize(
        {
            "title": "Legacy Campaign Strategy Route",
            "subtitle": "Experimental campaign route retained for explicit advertising requests",
            "selected_preset": "custom",
            "layout": "campaign-strategy-map",
            "style": "advertising-clean-campaign",
            "reader_question": "How does the campaign connect audience insight to measurable adoption?",
            "reader_path": ["Audience", "Insight", "Message", "Channels", "Measurement"],
            "metadata": {
                "created_by": "tech-route-maker",
                "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
                "source_type": "legacy-campaign",
                "source_files": [{"path": path, "kind": "document", "description": "Legacy campaign demo brief"}],
                "source_hashes": [],
                "language": "en",
                "audience": "campaign",
                "demo": True,
                "legacy": True,
            },
            "stages": [
                stage("audience", "Audience", 1, "Identify who the campaign must persuade.", [
                    node("audience_segments", "Map user segments", "Target researchers, lab managers, and academic teams.", "input", path, "Audience"),
                    node("audience_jobs", "Clarify workflow jobs", "Separate paper figures, proposal routes, and reporting needs.", "input", path, "Jobs"),
                ]),
                stage("insight", "Insight", 2, "Find the adoption driver.", [
                    node("insight_editable", "Lead with editability", "Emphasize editable, evidence-linked route diagrams.", "method", path, "Insight"),
                    node("insight_friction", "Remove drawing friction", "Show source-to-route workflow instead of manual redrawing.", "method", path, "Pain point"),
                ]),
                stage("message", "Message", 3, "Turn insight into positioning.", [
                    node("message_position", "Position workflow value", "Frame the tool as a source-to-editable-diagram workflow.", "method", path, "Positioning"),
                    node("message_proof", "Show demo proof", "Use README, gallery, and editable files as proof.", "implementation", path, "Proof"),
                ]),
                stage("channels", "Channels", 4, "Distribute proof-oriented content.", [
                    node("channels_github", "Use GitHub hub", "Anchor examples, install instructions, and release notes on GitHub.", "deployment", path, "GitHub"),
                    node("channels_content", "Publish demo content", "Share short videos, posts, and lab-demo decks.", "deployment", path, "Content"),
                ]),
                stage("measure", "Measurement", 5, "Connect content activity to adoption signals.", [
                    node("measure_metrics", "Track adoption signals", "Measure stars, demo runs, issue feedback, and trials.", "validation", path, "Metrics"),
                    node("measure_feedback", "Feed back issues", "Classify onboarding, layout, and output-format feedback.", "feedback", path, "Feedback"),
                ]),
            ],
            "edges": [
                edge("e1", "audience_segments", "audience_jobs", "segments"),
                edge("e2", "audience_jobs", "insight_editable", "reveals"),
                edge("e3", "insight_editable", "insight_friction", "frames"),
                edge("e4", "insight_friction", "message_position", "shapes"),
                edge("e5", "message_position", "message_proof", "proves"),
                edge("e6", "message_proof", "channels_github", "anchors"),
                edge("e7", "channels_github", "channels_content", "extends"),
                edge("e8", "channels_content", "measure_metrics", "drives"),
                edge("e9", "measure_metrics", "measure_feedback", "learns"),
                edge("e10", "measure_feedback", "message_position", "optimizes", "feedback"),
            ],
        }
    )


DEMOS = {
    "academic-paper-demo": (academic_route, "Academic paper demo brief for a PV surface defect detection method route."),
    "thesis-proposal-demo": (thesis_route, "Thesis proposal demo brief for PV self-cleaning coating research."),
    "engineering-energy-system-demo": (energy_route, "Engineering demo brief for a campus source-grid-load-storage energy system."),
    "agent-workflow-demo": (workflow_route, "Workflow demo brief for converting technical materials into editable route diagrams."),
    "legacy-campaign-route-demo": (campaign_route, "Legacy campaign demo brief retained only for explicit advertising requests."),
}


def write_brief(folder, text):
    target = ROOT / "examples" / folder / "brief.md"
    write_text(target, f"# {folder}\n\n{text}\n")


def render_demo(folder, route_factory):
    example_dir = ROOT / "examples" / folder
    out_dir = example_dir / "outputs"
    out_dir.mkdir(parents=True, exist_ok=True)
    route = route_factory()
    route_path = out_dir / "tech-route.json"
    write_text(route_path, json.dumps(route, ensure_ascii=False, indent=2) + "\n")
    subprocess.check_call([
        sys.executable,
        str(ROOT / "scripts" / "render_all.py"),
        str(route_path),
        str(out_dir),
        "--formats",
        CORE_FORMATS,
    ])


def svg_text(x, y, value, size, color, weight=400, anchor="middle"):
    return f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-family="Arial, Helvetica, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(value)}</text>'


def svg_rect(x, y, w, h, fill, stroke="#D7E0EA", rx=10, width=1.3):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>'


def asset_svg(width, height, compact=False):
    cards = [
        ("Academic", "#E8F3F1", "#315C61", ["Goal", "Data", "Method", "Validation"]),
        ("Proposal", "#F7E0E8", "#7BCFD0", ["Objective", "Content", "Technology", "Output"]),
        ("Engineering", "#E8EEF7", "#27456F", ["Boundary", "Model", "Control", "KPIs"]),
        ("Workflow", "#F4F5F7", "#475569", ["Intake", "Extract", "Render", "Review"]),
    ]
    title = "tech-route-maker" if compact else "Editable Technical Route Gallery"
    subtitle = "Evidence-grounded editable route diagrams for research and engineering"
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
        svg_rect(18, 18, width - 36, height - 36, "#FFFFFF", "#D8E1EA", 18, 1),
        svg_text(width // 2, 66 if compact else 82, title, 30 if compact else 38, "#172033", 700),
        svg_text(width // 2, 104 if compact else 124, subtitle, 15 if compact else 17, "#59636A", 400),
    ]
    start_x = 66
    card_y = 146 if compact else 190
    card_w = 250 if compact else 270
    card_h = 164 if compact else 360
    gap = 28 if compact else 32
    for i, (name, fill, accent, labels) in enumerate(cards):
        x = start_x + i * (card_w + gap)
        out.append(svg_rect(x, card_y, card_w, card_h, fill, "#C8D4E0", 14, 1.4))
        out.append(svg_rect(x + 18, card_y + 18, card_w - 36, 32, accent, accent, 8, 1))
        out.append(svg_text(x + card_w / 2, card_y + 39, name, 14, "#FFFFFF", 700))
        visible = labels[:3] if compact else labels
        for j, label in enumerate(visible):
            y = card_y + 68 + j * (34 if compact else 58)
            h = 24 if compact else 38
            out.append(svg_rect(x + 30, y, card_w - 60, h, "#FFFFFF", "#9DB3C5", 7, 1.1))
            out.append(svg_text(x + card_w / 2, y + h / 2 + 4, label, 11 if compact else 14, "#172033", 600))
            if j < len(visible) - 1:
                cx = x + card_w / 2
                out.append(f'<path d="M {cx} {y + h} L {cx} {y + (34 if compact else 58) - 2}" stroke="{accent}" stroke-width="1.6" marker-end="url(#arrow{i})"/>')
        out.append(f'<defs><marker id="arrow{i}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{accent}"/></marker></defs>')
    out.append(svg_text(width // 2, height - (24 if compact else 42), "Editable PPTX | SVG | Draw.io | HTML | Markdown | JSON", 13 if compact else 15, "#59636A", 600))
    out.append("</svg>")
    return "\n".join(out)


def write_assets():
    assets = ROOT / "assets"
    assets.mkdir(exist_ok=True)
    write_text(assets / "banner.svg", asset_svg(1280, 360, compact=True))
    write_text(assets / "demo-preview.svg", asset_svg(1280, 720, compact=False))
    write_text(assets / "social-preview.svg", asset_svg(1200, 630, compact=False))


def main():
    for folder, (factory, brief) in DEMOS.items():
        write_brief(folder, brief)
        render_demo(folder, factory)
    sample = ROOT / "examples" / "sample-tech-route.json"
    write_text(sample, json.dumps(academic_route(), ensure_ascii=False, indent=2) + "\n")
    write_assets()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
