import json
import subprocess
import sys
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FORMATS = "pptx,svg,drawio,excalidraw,html,markdown,json"


def evidence(path, note):
    return [{"kind": "document", "path": path, "note": note}]


def node(node_id, label, detail, tag, path, note):
    return {
        "id": node_id,
        "label": label,
        "detail": detail,
        "tag": tag,
        "evidence": evidence(path, note),
    }


def stage(stage_id, title, summary, nodes):
    return {"id": stage_id, "title": title, "summary": summary, "nodes": nodes}


def academic_route():
    path = "examples/academic-paper-demo/source/project-brief.md"
    return {
        "title": "多模态光伏缺陷检测技术路线图",
        "subtitle": "Academic method framework demo generated by tech-route-maker",
        "audience": "academic",
        "figure_subtype": "academic_method_framework",
        "layout": "academic-method-framework",
        "style": "premium-scientific",
        "reader_question": "该方法如何从多模态图像证据走向可验证的缺陷检测结果？",
        "reader_path": ["研究目标", "数据与样本", "方法设计", "训练优化", "验证输出"],
        "metadata": {
            "source_scope": path,
            "generated_by": "tech-route-maker",
            "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
            "demo": True,
        },
        "stages": [
            stage(
                "objective",
                "研究目标",
                "定义论文图需要回答的核心问题。",
                [
                    node("objective_task", "明确缺陷检测任务", "识别光伏组件图像中的缺陷类别、位置和置信度。", "objective", path, "Project goal"),
                    node("objective_metrics", "设定评价指标", "围绕 precision、recall、mAP 和推理效率组织验证逻辑。", "objective", path, "Evaluation target"),
                ],
            ),
            stage(
                "data",
                "数据与样本",
                "建立 RGB 与红外图像输入，并形成可训练样本。",
                [
                    node("data_capture", "采集多模态图像", "收集 RGB 图像和红外热图，作为缺陷检测的互补输入。", "input", path, "Input data"),
                    node("data_align", "配准与标注缺陷", "对齐 RGB/IR 图像，并标注缺陷边界或类别。", "input", path, "Alignment and annotation"),
                    node("data_split", "划分训练样本", "清洗低质量样本，划分训练、验证和测试数据。", "implementation", path, "Data split"),
                ],
            ),
            stage(
                "method",
                "方法设计",
                "突出论文方法的主要创新模块。",
                [
                    node("method_baseline", "建立基线检测器", "以通用目标检测器作为基础框架。", "method", path, "Baseline detector"),
                    node("method_fusion", "构建跨模态融合", "融合 RGB 与红外特征，提升缺陷区域表达能力。", "method", path, "Multimodal feature fusion"),
                    node("method_attention", "增强关键区域感知", "通过注意力或特征增强模块突出微弱缺陷。", "method", path, "Attention enhancement"),
                ],
            ),
            stage(
                "training",
                "训练优化",
                "从模型训练走向稳定推理。",
                [
                    node("training_loss", "设计损失函数", "结合定位、分类和置信度损失优化检测性能。", "implementation", path, "Loss design"),
                    node("training_ablation", "训练与消融实验", "逐项验证融合模块、增强模块和训练策略的贡献。", "validation", path, "Training and ablation"),
                    node("training_infer", "推理并筛选结果", "对未见图像执行推理，并按置信度筛选缺陷结果。", "implementation", path, "Inference and confidence filtering"),
                ],
            ),
            stage(
                "output",
                "验证输出",
                "把技术路线连接到论文证据和应用结果。",
                [
                    node("output_metrics", "完成指标评估", "通过基线对比、mAP、precision 和 recall 验证方法有效性。", "validation", path, "Quantitative metrics"),
                    node("output_visual", "生成可视化解释", "输出缺陷框、热区响应和失败案例，支撑论文图表。", "output", path, "Visualization"),
                    node("output_report", "输出缺陷报告", "形成缺陷类别、位置、置信度和维护建议。", "output", path, "Defect report"),
                ],
            ),
        ],
        "edges": [
            {"from": "objective_task", "to": "objective_metrics", "label": "defines"},
            {"from": "objective_metrics", "to": "data_capture", "label": "guides data"},
            {"from": "data_capture", "to": "data_align", "label": "aligns"},
            {"from": "data_align", "to": "data_split", "label": "prepares"},
            {"from": "data_split", "to": "method_baseline", "label": "feeds model"},
            {"from": "method_baseline", "to": "method_fusion", "label": "extends"},
            {"from": "method_fusion", "to": "method_attention", "label": "enhances"},
            {"from": "method_attention", "to": "training_loss", "label": "optimizes"},
            {"from": "training_loss", "to": "training_ablation", "label": "tests"},
            {"from": "training_ablation", "to": "training_infer", "label": "selects"},
            {"from": "training_infer", "to": "output_metrics", "label": "evaluates"},
            {"from": "output_metrics", "to": "output_visual", "label": "explains"},
            {"from": "output_visual", "to": "output_report", "label": "reports"},
        ],
    }


def thesis_route():
    path = "examples/thesis-proposal-demo/source/project-brief.md"
    return {
        "title": "PV Module Degradation Assessment Technical Route",
        "subtitle": "Thesis proposal route generated by tech-route-maker",
        "audience": "academic",
        "figure_subtype": "thesis_proposal_route",
        "layout": "proposal-matrix-route",
        "style": "proposal-pastel-route",
        "reader_question": "How does the thesis move from monitoring evidence to defensible degradation-risk assessment?",
        "reader_path": ["Research objective", "Research content", "Key technologies", "Experimental validation", "Expected outputs"],
        "metadata": {
            "source_scope": path,
            "generated_by": "tech-route-maker",
            "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
            "demo": True,
        },
        "stages": [
            stage("objective", "Research Objective", "Define the thesis problem and expected contribution.", [
                node("objective_problem", "Define degradation risk", "Link outdoor monitoring evidence to photovoltaic module degradation risk.", "objective", path, "Research problem"),
                node("objective_scope", "Set evaluation scope", "Focus the route on risk grade, contributing factors, and inspection priority.", "objective", path, "Scope"),
            ]),
            stage("content", "Research Content", "Convert field evidence into analyzable indicators.", [
                node("content_collect", "Collect field evidence", "Use inspection records, I-V curves, infrared images, weather logs, and maintenance notes.", "input", path, "Inputs"),
                node("content_clean", "Clean and align records", "Align time series, screen abnormal samples, and prepare train/test splits.", "implementation", path, "Data preparation"),
                node("content_indicators", "Construct indicators", "Build degradation indicators from electrical, thermal, environmental, and maintenance features.", "method", path, "Indicator construction"),
            ]),
            stage("technology", "Key Technologies", "Build interpretable and uncertainty-aware risk modeling.", [
                node("technology_select", "Select feature groups", "Choose interpretable feature groups that support model explanation and ablation.", "method", path, "Feature selection"),
                node("technology_model", "Fit risk model", "Map indicators to degradation-risk scores and factor explanations.", "method", path, "Risk model"),
                node("technology_uncertainty", "Estimate uncertainty", "Attach uncertainty labels to risk estimates for cautious thesis claims.", "validation", path, "Uncertainty labeling"),
            ]),
            stage("validation", "Experimental Validation", "Check whether the route supports defensible conclusions.", [
                node("validation_cases", "Validate fault cases", "Compare with historical fault cases and cross-site evidence.", "validation", path, "Historical cases"),
                node("validation_ablation", "Review feature ablation", "Ablate feature groups and use expert review to confirm result logic.", "validation", path, "Ablation and expert review"),
            ]),
            stage("output", "Expected Outputs", "Deliver thesis-ready interpretation and inspection priority.", [
                node("output_priority", "Output inspection priority", "Provide risk grade, contributing factors, and recommended inspection priority.", "output", path, "Output"),
                node("output_thesis", "Support thesis chapters", "Connect the route to method, experiment, result, and discussion chapters.", "output", path, "Thesis structure"),
            ]),
        ],
        "edges": [
            {"from": "objective_problem", "to": "objective_scope", "label": "scopes"},
            {"from": "objective_scope", "to": "content_collect", "label": "requires evidence"},
            {"from": "content_collect", "to": "content_clean", "label": "prepares"},
            {"from": "content_clean", "to": "content_indicators", "label": "constructs"},
            {"from": "content_indicators", "to": "technology_select", "label": "filters"},
            {"from": "technology_select", "to": "technology_model", "label": "trains"},
            {"from": "technology_model", "to": "technology_uncertainty", "label": "qualifies"},
            {"from": "technology_uncertainty", "to": "validation_cases", "label": "tests"},
            {"from": "validation_cases", "to": "validation_ablation", "label": "checks"},
            {"from": "validation_ablation", "to": "output_priority", "label": "supports"},
            {"from": "output_priority", "to": "output_thesis", "label": "writes"},
        ],
    }


def software_route():
    path = "examples/software-architecture-demo/source/project-brief.md"
    return {
        "title": "Document Intelligence System Technical Route",
        "subtitle": "Editable system architecture route generated by tech-route-maker",
        "audience": "engineering",
        "figure_subtype": "software_architecture_route",
        "layout": "software-system-route",
        "style": "schematic-precision",
        "reader_question": "How does the system transform user files into validated analytical artifacts?",
        "reader_path": ["User input", "Data layer", "Service layer", "Rendering layer", "Quality release"],
        "metadata": {
            "source_scope": path,
            "generated_by": "tech-route-maker",
            "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
            "demo": True,
        },
        "stages": [
            stage("input", "User Input", "Collect user-provided files and configuration.", [
                node("input_files", "Receive files", "Accept documents, spreadsheets, PDFs, and user configuration as project evidence.", "input", path, "Inputs"),
                node("input_options", "Capture output choices", "Record selected formats, layout, style, and evidence preferences.", "input", path, "Configuration"),
            ]),
            stage("data", "Data Layer", "Normalize source material for downstream analysis.", [
                node("data_ingest", "Ingest sources", "Coordinate upload intake, metadata extraction, and parser-worker dispatch.", "implementation", path, "Ingestion service"),
                node("data_store", "Build normalized store", "Persist source metadata, parsed records, and evidence links.", "implementation", path, "Normalized data store"),
                node("data_trace", "Track provenance", "Attach source paths, validation status, and node-level evidence.", "validation", path, "Provenance tracking"),
            ]),
            stage("service", "Service Layer", "Build the route model and enforce diagram rules.", [
                node("service_extract", "Extract route model", "Identify stages, nodes, edges, outputs, and feedback loops from source evidence.", "method", path, "Route extraction"),
                node("service_schema", "Validate schema", "Check node ids, evidence, selected output formats, and edge endpoints.", "validation", path, "Validation rules"),
                node("service_layout", "Select template family", "Map the route to academic, proposal, system, or campaign templates.", "method", path, "Layout selection"),
            ]),
            stage("render", "Rendering Layer", "Render editable user-facing artifacts.", [
                node("render_svg", "Render SVG/HTML", "Generate vector preview and interactive inspection view.", "output", path, "SVG and HTML"),
                node("render_pptx", "Render PPTX shapes", "Create native slide shapes, text boxes, and connectors for editing.", "output", path, "PPTX"),
                node("render_drawio", "Render Draw.io cells", "Export editable diagrams.net nodes and edges for maintenance.", "output", path, "Draw.io"),
            ]),
            stage("quality", "Quality Release", "Validate outputs before handoff.", [
                node("quality_visual", "Run visual QA", "Check layout, text wrapping, connector direction, and README paths.", "validation", path, "Visual QA"),
                node("quality_publish", "Publish examples", "Commit regenerated demos and keep release examples reproducible.", "deployment", path, "Release route"),
            ]),
        ],
        "edges": [
            {"from": "input_files", "to": "input_options", "label": "configures"},
            {"from": "input_options", "to": "data_ingest", "label": "starts"},
            {"from": "data_ingest", "to": "data_store", "label": "normalizes"},
            {"from": "data_store", "to": "data_trace", "label": "links"},
            {"from": "data_trace", "to": "service_extract", "label": "grounds"},
            {"from": "service_extract", "to": "service_schema", "label": "checks"},
            {"from": "service_schema", "to": "service_layout", "label": "routes"},
            {"from": "service_layout", "to": "render_svg", "label": "renders"},
            {"from": "service_layout", "to": "render_pptx", "label": "renders"},
            {"from": "service_layout", "to": "render_drawio", "label": "renders"},
            {"from": "render_pptx", "to": "quality_visual", "label": "reviews"},
            {"from": "quality_visual", "to": "quality_publish", "label": "releases"},
        ],
    }


def campaign_route():
    path = "examples/campaign-route-demo/source/campaign-brief.md"
    return {
        "title": "Research Tool Launch Campaign Strategy Route",
        "subtitle": "Campaign route generated by tech-route-maker",
        "audience": "advertising",
        "figure_subtype": "campaign_route",
        "layout": "campaign-strategy-map",
        "style": "advertising-clean-campaign",
        "reader_question": "How does the campaign move from audience insight to measurable adoption?",
        "reader_path": ["Audience", "Insight", "Message", "Channels", "Measurement", "Optimization"],
        "metadata": {
            "source_scope": path,
            "generated_by": "tech-route-maker",
            "selected_output_formats": ["pptx", "svg", "drawio", "html", "markdown", "json"],
            "demo": True,
        },
        "stages": [
            stage("audience", "Audience", "Identify who the campaign must persuade.", [
                node("audience_segments", "Map user segments", "Target graduate students, lab managers, and academic teams with different workflow needs.", "input", path, "Audience"),
                node("audience_jobs", "Clarify workflow jobs", "Separate paper figures, proposal routes, and team reporting needs.", "input", path, "Jobs to be done"),
            ]),
            stage("insight", "Insight", "Find the trust driver behind adoption.", [
                node("insight_editable", "Lead with editability", "Users trust outputs more when visuals remain editable and evidence-linked.", "method", path, "Insight"),
                node("insight_friction", "Remove drawing friction", "Show how source material becomes a usable route without manual redrawing.", "method", path, "Pain point"),
            ]),
            stage("message", "Message", "Translate insight into campaign positioning.", [
                node("message_positioning", "Position workflow value", "Frame the product as source-to-editable-diagram workflow.", "method", path, "Strategy"),
                node("message_proof", "Show before and after", "Use problem hook, evidence-first promise, demo output, and use-case proof.", "implementation", path, "Creative route"),
            ]),
            stage("channels", "Channels", "Distribute proof-oriented content.", [
                node("channels_github", "Use GitHub as hub", "Anchor the campaign in README, examples, templates, and visible demo outputs.", "deployment", path, "GitHub README"),
                node("channels_content", "Publish demo content", "Share short video, social posts, lab demo deck, and community templates.", "deployment", path, "Channel route"),
            ]),
            stage("measurement", "Measurement", "Connect channel activity to adoption signals.", [
                node("measurement_metrics", "Track adoption signals", "Measure stars, demo runs, template downloads, issue feedback, and trials.", "validation", path, "Measurement"),
                node("measurement_feedback", "Collect quality feedback", "Classify layout, output-format, and user onboarding issues.", "validation", path, "Feedback"),
            ]),
            stage("optimization", "Optimization", "Improve the message and examples over time.", [
                node("optimization_route", "Optimize message route", "Refine messaging based on drop-off, issue themes, and output-quality feedback.", "feedback", path, "Optimization"),
            ]),
        ],
        "edges": [
            {"from": "audience_segments", "to": "audience_jobs", "label": "segments"},
            {"from": "audience_jobs", "to": "insight_editable", "label": "reveals"},
            {"from": "insight_editable", "to": "insight_friction", "label": "frames"},
            {"from": "insight_friction", "to": "message_positioning", "label": "shapes"},
            {"from": "message_positioning", "to": "message_proof", "label": "proves"},
            {"from": "message_proof", "to": "channels_github", "label": "anchors"},
            {"from": "channels_github", "to": "channels_content", "label": "extends"},
            {"from": "channels_content", "to": "measurement_metrics", "label": "drives"},
            {"from": "measurement_metrics", "to": "measurement_feedback", "label": "learns"},
            {"from": "measurement_feedback", "to": "optimization_route", "label": "optimizes"},
            {"from": "optimization_route", "to": "message_positioning", "label": "iterates", "kind": "feedback"},
        ],
    }


DEMOS = {
    "academic-paper-demo": academic_route,
    "thesis-proposal-demo": thesis_route,
    "software-architecture-demo": software_route,
    "campaign-route-demo": campaign_route,
}


def svg_text(x, y, value, size, color, weight=400, anchor="middle"):
    return f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-family="Arial, Helvetica, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(value)}</text>'


def svg_rect(x, y, w, h, fill, stroke="#D7E0EA", rx=12, width=1.3, extra=""):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="{width}" {extra}/>'


def asset_svg(width, height, title, subtitle, compact=False):
    cards = [
        ("Academic Method", "#E8F3F1", "#315C61", ["Goal", "Data", "Method", "Validation"]),
        ("Proposal Route", "#F7E0E8", "#7BCFD0", ["Objective", "Content", "Technology", "Output"]),
        ("System Route", "#F3F4F6", "#374151", ["Input", "Data", "Service", "Release"]),
        ("Campaign Map", "#FFE4E6", "#E11D48", ["Audience", "Message", "Channels", "KPI"]),
    ]
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
        svg_rect(18, 18, width - 36, height - 36, "#FFFFFF", "#D8E1EA", 22, 1),
        svg_text(width // 2, 70 if compact else 82, title, 32 if compact else 38, "#172033", 700),
        svg_text(width // 2, 106 if compact else 124, subtitle, 15 if compact else 17, "#59636A", 400),
    ]
    if compact:
        start_x, card_y, card_w, card_h, gap = 70, 160, 245, 270, 28
    else:
        start_x, card_y, card_w, card_h, gap = 70, 190, 270, 360, 32
    for i, (name, fill, accent, labels) in enumerate(cards):
        x = start_x + i * (card_w + gap)
        out.append(svg_rect(x, card_y, card_w, card_h, fill, "#C8D4E0", 16, 1.4))
        out.append(svg_rect(x + 18, card_y + 18, card_w - 36, 36, accent, accent, 10, 1))
        out.append(svg_text(x + card_w / 2, card_y + 42, name, 15, "#FFFFFF", 700))
        for j, label in enumerate(labels):
            y = card_y + 82 + j * (44 if compact else 58)
            out.append(svg_rect(x + 30, y, card_w - 60, 30 if compact else 38, "#FFFFFF", "#9DB3C5", 8, 1.2))
            out.append(svg_text(x + card_w / 2, y + (20 if compact else 25), label, 12 if compact else 14, "#172033", 600))
            if j < len(labels) - 1:
                cx = x + card_w / 2
                out.append(f'<path d="M {cx} {y + (30 if compact else 38)} L {cx} {y + (42 if compact else 56)}" stroke="{accent}" stroke-width="1.6" marker-end="url(#arrow{i})"/>')
        out.append(f'<defs><marker id="arrow{i}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="{accent}"/></marker></defs>')
    out.append(svg_text(width // 2, height - 48, "Editable SVG · Native PPTX shapes · Draw.io cells · HTML preview", 15, "#59636A", 600))
    out.append("</svg>")
    return "\n".join(out)


def write_assets():
    assets = ROOT / "assets"
    assets.mkdir(exist_ok=True)
    (assets / "banner.svg").write_text(
        asset_svg(1280, 360, "tech-route-maker", "Source-grounded editable technical route diagrams for academic and campaign work", compact=True),
        encoding="utf-8",
        newline="\n",
    )
    (assets / "demo-preview.svg").write_text(
        asset_svg(1280, 720, "Editable Technical Route Gallery", "Four template families regenerated as editable route diagrams", compact=False),
        encoding="utf-8",
        newline="\n",
    )
    (assets / "social-preview.svg").write_text(
        asset_svg(1200, 630, "tech-route-maker", "Editable technical route diagrams: PPTX, SVG, Draw.io, HTML", compact=False),
        encoding="utf-8",
        newline="\n",
    )


def write_schema_doc():
    content = """# Route Schema

`tech-route.json` is the source of truth for rendering. Edit the JSON first, then rerender PPTX, SVG, Draw.io, Excalidraw, Mermaid, HTML, Markdown, or JSON outputs from the same model.

## Minimal Structure

```json
{
  "title": "Project Technical Route",
  "subtitle": "Editable route diagram",
  "layout": "academic-method-framework",
  "style": "academic-blue",
  "metadata": {
    "selected_output_formats": ["pptx", "svg", "json"]
  },
  "stages": [
    {
      "id": "objective",
      "title": "Objective",
      "nodes": [
        {
          "id": "objective_goal",
          "label": "Define project goal",
          "detail": "Clarify the problem and expected result.",
          "tag": "objective",
          "evidence": [
            {"kind": "document", "path": "source.md", "note": "Project goal"}
          ]
        }
      ]
    }
  ],
  "edges": [
    {"from": "objective_goal", "to": "next_node", "label": "guides"}
  ]
}
```

## Practical Rules

- Keep the main route to 4 to 7 stages.
- Keep each stage to 2 to 6 nodes.
- Keep visible labels short.
- Put long explanations in `detail`, Markdown, or HTML.
- Use `evidence` for every node.
- Use `metadata.selected_output_formats` to record the user's explicit choices.

## Layout Values

- `academic-method-framework`: default academic template for papers, defenses, and research reports.
- `proposal-matrix-route`: thesis proposal, grant route, and research-plan route.
- `software-system-route`: software architecture, system engineering, and platform workflow.
- `campaign-strategy-map`: advertising strategy, campaign workflow, channel route, and optimization map.
- `proposal-phase-axis`: legacy long vertical route with a left phase axis; do not use it as the default Gallery/README example.

---

# 路线 Schema

`tech-route.json` 是渲染源文件。修改标题、阶段、节点、连接、风格或输出格式后，可以重新运行 `render_all.py` 生成新的可编辑文件。

## 实用规则

- 主路线建议保留 4 到 7 个阶段。
- 每个阶段建议 2 到 6 个节点。
- 可见标签要短，长解释放在 `detail`、Markdown 或 HTML 面板中。
- 每个节点都应有 `evidence`，或者明确标记为推断。
- `metadata.selected_output_formats` 用来记录用户明确选择的输出格式。
"""
    (ROOT / "docs" / "schema.md").write_text(content, encoding="utf-8", newline="\n")


def render_demo(name, route_factory):
    out_dir = ROOT / "examples" / name / "outputs"
    out_dir.mkdir(parents=True, exist_ok=True)
    route_path = out_dir / "tech-route.json"
    route = route_factory()
    route_path.write_text(json.dumps(route, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    subprocess.check_call([sys.executable, str(ROOT / "scripts" / "render_all.py"), str(route_path), str(out_dir), "--formats", FORMATS])


def main():
    for name, factory in DEMOS.items():
        render_demo(name, factory)
    write_assets()
    write_schema_doc()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
